### ISSUE TITLE
Make memcached-session-manager work with Tomcat 7.x

### ISSUE THREAD

**Issue by google-code-exporter** [magro/memcached-session-manager#120]
_From [ile...@gmail.com](https://code.google.com/u/107722982579522612064/) on January 19, 2011 19:13:35_

<b>What steps will reproduce the problem?</b>
1. Configure memcached-session-manager to be used with Tomcat 7.x&#13;
&#13;
<b>What is the expected output? What do you see instead?</b>
&#13;
Expected: Should work normally&#13;
&#13;
Result:&#13;
&#13;
Jan 19, 2011 1:11:25 PM org.apache.tomcat.util.digester.Digester startElement&#13;
SEVERE: Begin event threw error&#13;
java.lang.VerifyError: class de.javakaffee.web.msm.MemcachedBackupSessionManager overrides final method init.()V&#13;
	at java.lang.ClassLoader.defineClass1(Native Method)&#13;
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:632)&#13;
[...]&#13;
&#13;
<b>What version of the product are you using? On what operating system?</b>
&#13;
Tomcat 7.9.6 on CentOS Linux x86_64&#13;
&#13;
<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=77_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on January 20, 2011 00:45:42_

I assume you're referring to Tomcat 7.0.6.

There's already a tomcat7 branch existing. I just built against released tomcat 7.0.6 and made some minor adaptions, so that all tests are green again.

I uploaded a jar to
  <a href="http://dl.dropbox.com/u/1439289/memcached-session-manager-1.4.0-tc7-SNAPSHOT.jar" rel="nofollow">http://dl.dropbox.com/u/1439289/memcached-session-manager-1.4.0-tc7-SNAPSHOT.jar</a>&#13;
&#13;
Other jars can be used as linked on <a title="This page shows what's necessary to get the memcached-session-manager up and running." href="/p/memcached-session-manager/wiki/SetupAndConfiguration">SetupAndConfiguration</a>.&#13;
&#13;
The tomcat7 build will be part of the next release which I'm going to push out the next weeks.

**Status:** Started  
  **Labels:** -Type-Defect Type-Enhancement

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on January 27, 2011 14:36:22_

<i>(No comment was entered for this change.)</i>

**Labels:** Milestone-1.4.0

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on January 27, 2011 23:27:55_

Released with 1.4.0 as package memcached-session-manager-tc7

**Status:** Fixed
