### ISSUE TITLE
Tomcat doesn't start in TestUtils on Windows - backslash escape needed

### ISSUE THREAD

**Issue by google-code-exporter** [magro/memcached-session-manager#130]
_From [rainer.j...@kippdata.de](https://code.google.com/u/102517300929192813948/) on March 09, 2011 13:21:48_

Building trunk and 1.3.6 doesn't work on Windows, because TestUtils uses the File.separator as a replacement in replaceAll(). But backslashes have a special meaning there.

Possible trivial patch attached.

**Attachment:** [quoteBackslash.patch](http://code.google.com/p/memcached-session-manager/issues/detail?id=87)

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=87_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on March 09, 2011 05:01:23_

I'd suspect that with this patch tests don't run through even on windows, as

"foo.bar.baz".replaceAll( "\\.", Pattern.quote( "\\" ) );

gives me "fooQ\EbarQ\Ebaz" which is not expected (expected on windows: "foo\bar\baz")

Therefore I'm using "\\\\" as replacement for the dots for windows.

Pushed in master and tomcat7 branch. Can you confirm that this is working for you?

**Status:** Started

**Comment by google-code-exporter** [comment]
_From [rainer.j...@kippdata.de](https://code.google.com/u/102517300929192813948/) on March 09, 2011 05:32:57_

Yes, sorry the patch was nonsense. I hoped to provide a better one before you take a look, but there was lunch break before :)

Your patch works fine. Still two tests failing but seemingly unrelated.

testNonStickySessionIsStoredInSecondaryMemcachedForBackup fails likely because there is no secondary memcached on the test system. The other failing test is testChangeSessionId(NON_STICKY). It fails in line

verify( _memcachedMock, times( 1 ) ).set( eq( session.getId() ), anyInt(), any() );

with message:

Argument(s) are different! Wanted:
memcachedClient.set(
    "E7400A2744F820E192F9FB4B68D5B044-n1",
    <any>,
    <any>
);
-> at de.javakaffee.web.msm.MemcachedBackupSessionManagerTest.testChangeSessionId(MemcachedBackupSessionManagerTest.java:254)
Actual invocation has different arguments:
memcachedClient.set(
    "validity:04476FA52995AACD01CA4BDEB8D497F4-n1",
    1800,
    [0, 0, 7, 8, 0, 0, 1, 46, -102, -61, -45, 110, 0, 0, 1, 46, -102, -61, -45, 110]
);
-> at de.javakaffee.web.msm.LockingStrategy.onAfterBackupSession(LockingStrategy.java:270)

        at de.javakaffee.web.msm.MemcachedBackupSessionManagerTest.testChangeSessionId(MemcachedBackupSessionManagerTest.java:254)
... Removed 22 stack frames
FAILED: testNonStickySessionIsStoredInSecondaryMemcachedForBackup
java.lang.AssertionError: expected:<true> but was:<false>
        at de.javakaffee.web.msm.integration.NonStickySessionsIntegrationTest.testNonStickySessionIsStoredInSecondaryMemcachedForBackup(NonStickySessionsIntegrationTest.java:437)
... Removed 27 stack frames

Is it an expected failure? Should I open an issue for this test failure?
It seems there's no discussion list (or I didn't find it).

**Comment by google-code-exporter** [comment]
_From [rainer.j...@kippdata.de](https://code.google.com/u/102517300929192813948/) on March 09, 2011 05:37:37_

Sorry, more test failures I overlooked:

de.javakaffee.web.msm.MemcachedBackupSessionManagerTest
de.javakaffee.web.msm.MemcachedSessionManagerIntegrationTest
de.javakaffee.web.msm.SessionTrackerValveTest
de.javakaffee.web.msm.TranscoderServiceTest
de.javakaffee.web.msm.integration.MemcachedFailoverIntegrationTest
de.javakaffee.web.msm.integration.NonStickySessionsIntegrationTest
de.javakaffee.web.msm.integration.TomcatFailoverIntegrationTest
de.javakaffee.web.msm.serializer.hibernate.JavaSerializationHibernateCollectionsTest

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on March 09, 2011 06:06:09_

Ok, so I close this issue now as the backslash-thing is fixed.

The mailing list is at <a href="http://groups.google.com/group/memcached-session-manager" rel="nofollow">http://groups.google.com/group/memcached-session-manager</a> (the link is on the home page left bottom).&#13;
&#13;
If you can open an issue for these 2 failing tests it would be great (are they failing when running with buildr, from eclipse/IDE?)! Other tests might be reported by buildr as failed as they're following the other ones. You can run a single test via e.g.&#13;
$ buildr test:MemcachedBackupSessionManagerTest&#13;

**Status:** Fixed  
  **Labels:** Milestone-1.4.1
