### ISSUE TITLE
Redundant retrieval of session from memcached after TC failover (with jvmRoute + securityConstraint/Valve)

### ISSUE THREAD

**Issue by google-code-exporter** [magro/memcached-session-manager#136]
_From [rainer.j...@kippdata.de](https://code.google.com/u/102517300929192813948/) on March 23, 2011 15:05:53_

Observed for the TC 7 branch, but likely not restricted to that.

Directly after Tomcat failover the session is retrieved twice from memcached. This is due to an internal Tomcat valve already accessing the session before your own SessionTrackerValve runs.

Please ignore line numbers in the below given stacks. I added lots of debug statements, so lines were shifted.

First time (example):

        at de.javakaffee.web.msm.MemcachedBackupSessionManager.loadFromMemcached(MemcachedBackupSessionManager.java:917)
        at de.javakaffee.web.msm.MemcachedBackupSessionManager.findSession(MemcachedBackupSessionManager.java:535)
        at org.apache.catalina.connector.Request.doGetSession(Request.java:2686)
        at org.apache.catalina.connector.Request.getSessionInternal(Request.java:2411)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:452)
...
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:394)

Second time (same request):

        at de.javakaffee.web.msm.MemcachedBackupSessionManager.loadFromMemcached(MemcachedBackupSessionManager.java:917)
        at de.javakaffee.web.msm.MemcachedBackupSessionManager.loadFromMemcachedWithCheck(MemcachedBackupSessionManager.java:892)
        at de.javakaffee.web.msm.MemcachedBackupSessionManager.changeSessionIdOnTomcatFailover(MemcachedBackupSessionManager.java:646)
        at de.javakaffee.web.msm.SessionTrackerValve.changeRequestedSessionId(SessionTrackerValve.java:200)
        at de.javakaffee.web.msm.SessionTrackerValve.invoke(SessionTrackerValve.java:128)

Since this could also happen with other Valves, it might make sense to check, wheher the session has already been retrieved to reduce dublicate work (and latency).

I didn't yet work on a patch :(

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=93_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on March 23, 2011 13:09:28_

<i>(No comment was entered for this change.)</i>

**Summary:** Redundant retrieval of session from memcached after TC failover (with jvmRoute set)  
  **Status:** Accepted  
  **Owner:** martin.grotzke

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on March 25, 2011 16:25:15_

Fixed together with <a title="Incomplete change of session ID after Tomcat failover (with jvmRoute + securityConstraint/Valve)" class="closed_ref" href="/p/memcached-session-manager/issues/detail?id=92"> issue 92 </a> in master and tomcat7 branch.

**Summary:** Redundant retrieval of session from memcached after TC failover (with jvmRoute + securityConstraint/Valve)  
  **Status:** Fixed  
  **Labels:** Milestone-1.4.1

**Comment by google-code-exporter** [comment]
_From [rainer.j...@kippdata.de](https://code.google.com/u/102517300929192813948/) on March 31, 2011 09:08:05_

Yes, problem fixed. Works here too :)
