### ISSUE TITLE
NoClassDefFoundError ProtocolVersion

### ISSUE THREAD

**Issue by google-code-exporter** [magro/memcached-session-manager#203]
_From [mmartin2...@gmail.com](https://code.google.com/u/111729023302584768038/) on May 08, 2013 01:08:49_

<b>What steps will reproduce the problem?</b>
1. added this to my web app context.xml&#13;
&lt;Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"&#13;
      memcachedNodes="n1:xxxtest-sess1.xxx.com:xxxxx"&#13;
      requestUriIgnorePattern=".*\.(ico|png|gif|jpg|css|js)$"&#13;
      transcoderFactoryClass="de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory" /&gt;&#13;
&#13;
2. start up tomcat&#13;
&#13;
What is the expected output? Not getting any errors&#13;
What do you see instead?&#13;
May 7, 2013 3:30:54 PM de.javakaffee.web.msm.MemcachedSessionService updateExpirationInMemcached&#13;
INFO: Could not update expiration in memcached for session E31094818C0C1B10C54A0C79D1F77D85-n1.xxxtest-app2&#13;
java.lang.NoClassDefFoundError: org/apache/http/ProtocolVersion&#13;
	at java.lang.Class.getDeclaredFields0(Native Method)&#13;
	at java.lang.Class.privateGetDeclaredFields(Class.java:2308)&#13;
	at java.lang.Class.getDeclaredFields(Class.java:1760)&#13;
	at com.esotericsoftware.kryo.serialize.FieldSerializer.rebuildCachedFields(FieldSerializer.java:61)&#13;
&#13;
What version of the product are you using? &#13;
memcache 1.4.13&#13;
kyro 1.6.4&#13;
&#13;
On what operating system?&#13;
ubuntu&#13;
&#13;
&#13;
<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=162_

**Comment by google-code-exporter** [comment]
_From [mmartin2...@gmail.com](https://code.google.com/u/111729023302584768038/) on May 07, 2013 16:12:47_

also: memcached-session-manager-1.6.4.jar,memcached-session-manager-tc6-1.6.4.jar,spymemcached-2.8.4.jar,couchbase-client-1.1.4.jar

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on May 07, 2013 23:03:55_

Which version of tomcat are you using?

**Comment by google-code-exporter** [comment]
_From [mmartin2...@gmail.com](https://code.google.com/u/111729023302584768038/) on May 08, 2013 08:24:13_

Tomcat 6 - we got this solved by adding in the httpcore jar that was needed

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on May 08, 2013 12:47:15_

Was it an inconsistency in your deployment, or what was the issue?

**Comment by google-code-exporter** [comment]
_From [mmartin2...@gmail.com](https://code.google.com/u/111729023302584768038/) on May 08, 2013 12:54:27_

I am not sure if we are even using couchbase but the couchbase jar got deployed without all the other jars it requires so it refused to start up until we got the other jars in there

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on May 08, 2013 12:57:33_

Ok, so it's in line with the documentation. Closing.

**Status:** Invalid
