### ISSUE TITLE
node failure handling fails due to spymemcached 2.7.3 to 2.8.12 update

### ISSUE THREAD

**Issue by google-code-exporter** [magro/memcached-session-manager#208]
_From [hajo.kli...@gmail.com](https://code.google.com/u/108722860653807490848/) on July 01, 2013 17:17:14_

<b>What steps will reproduce the problem?</b>
1. start tomcat&#13;
2. shutdown couchbase cluster&#13;
3. enter tomcat page&#13;
4. start couchbase cluster&#13;
5. enter tomcat page&#13;
&#13;
Version: 1.6.5&#13;
&#13;
With the change of spymemcached 2.7.3 to 2.8.12 the split of couchbase/memcached library was made. With this change an undetected change was made to the connection factory that is responsible for redistributing requests that are addressed to a dead node (before BinaryConnectionFactory, now CouchbaseConnectionFactoryBuilder). the attribute that is used to determine the failure handling is CouchbaseConnectionFactory.DEFAULT_FAILURE_MODE = FailureMode.Retry (before: DefaultConnectionFactory.DEFAULT_FAILURE_MODE = FailureMode.Redistribute).&#13;
&#13;
this results in continous requests to a dead node that are already canceled and should be switched back&#13;
&#13;
Redistribute: In this failure mode, the failure of a node will cause its current queue and future requests to move to the next logical node in the cluster for a given key.&#13;
Retry: This failure mode is appropriate when you have a rare short downtime of a memcached node that will be back quickly, and your app is written to not wait very long for async command completion.&#13;
&#13;
Reconnecting {QA sa=localhost/127.0.0.1:11210, #Rops=0, #Wops=6, #iq=0, topRop=null, topWop=Cmd: 0 Op&#13;
Connection state changed for sun.nio.ch.SelectionKeyImpl@16ab5303&#13;
Reconnecting due to exception on {QA sa=localhost/127.0.0.1:11210, #Rops=7, #Wops=0, #iq=0, topRop=Cm&#13;
java.io.IOException: Disconnected unexpected, will reconnect.&#13;
        at net.spy.memcached.MemcachedConnection.handleReads(MemcachedConnection.java:526)&#13;
        at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:430)&#13;
        at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:247)&#13;
        at com.couchbase.client.CouchbaseConnection.run(CouchbaseConnection.java:265)&#13;
Closing, and reopening {QA sa=localhost/127.0.0.1:11210, #Rops=7, #Wops=0, #iq=0, topRop=Cmd: 0 Opaqu&#13;
Discarding partially completed op: Cmd: 0 Opaque: 238 Key: 1B3A927693D62D89DFD1595A5&#13;
Discarding partially completed op: Cmd: 0 Opaque: 239 Key: 1B3A927693D62D89DFD1595A5&#13;
Could not load session with id 1B3A927693D62D89DFD1595A521E6F61 from memcached.&#13;
java.util.concurrent.CancellationException: Cancelled&#13;
        at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:170)&#13;
        at net.spy.memcached.internal.GetFuture.get(GetFuture.java:62)&#13;
        at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1026)&#13;
        at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1051)&#13;
        at de.javakaffee.web.msm.MemcachedSessionService.loadFromMemcached(MemcachedSessionService.java:1112)&#13;
&#13;
pull request: <a href="https://github.com/magro/memcached-session-manager/pull/27" rel="nofollow">https://github.com/magro/memcached-session-manager/pull/27</a>&#13;

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=167_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on July 01, 2013 08:40:22_

Ouch, good catch!

For couchbase I agree that FailureMode.Redistribute is the correct choice.
For memcached though I'd say FailureMode.Cancel should be used, so that msm can kick in with its redistribution (I wonder why this was not covered before). What do you think?

**Status:** Accepted

**Comment by google-code-exporter** [comment]
_From [hajo.kli...@gmail.com](https://code.google.com/u/108722860653807490848/) on July 02, 2013 08:16:51_

i'm not using memcached but i think it is not a good idea to cancel the whole operation. if you got multiple memcached instances, on each instance the session is stored. if one instance goes down, i think it is a better idea to redistribute the operation to the running one

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on August 24, 2013 15:22:56_

Fixed, pull request is merged.

I also checked the failure mode for memcached connections and it's in fact set to Cancel already (in msm specific connection factories).

**Status:** Fixed  
  **Labels:** Milestone-1.6.6

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on December 20, 2013 14:20:35_

<i>(No comment was entered for this change.)</i>

**Labels:** -Milestone-1.6.6 Milestone-1.7.0
