### ISSUE TITLE
msm requires couchbase jars even when not using couchbase

### ISSUE THREAD

**Issue by google-code-exporter** [magro/memcached-session-manager#218]
_From [dlee.cal...@gmail.com](https://code.google.com/u/109176638585404116752/) on September 03, 2013 16:05:13_

<b>What steps will reproduce the problem?</b>
1. Install (or upgrade) msm from 1.6.3 to 1.6.5&#13;
NOT using spymemcached but rather using ElastiCache jar&#13;
2. Start Tomcat&#13;
&#13;
&#13;
<b>What is the expected output? What do you see instead?</b>
Expect: Tomcat and msm run.&#13;
Got: tomcat fails to start due to missing classs&#13;
&#13;
SEVERE: Begin event threw error&#13;
java.lang.NoClassDefFoundError: com/couchbase/client/CouchbaseClient&#13;
        at de.javakaffee.web.msm.MemcachedBackupSessionManager.&lt;init&gt;(MemcachedBackupSessionManager.java:80)&#13;
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)&#13;
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
        at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
        at java.lang.Class.newInstance0(Unknown Source)&#13;
&#13;
<b>What version of the product are you using? On what operating system?</b>
&#13;
Amazon Linux &#13;
msm 1.6.5&#13;
&#13;
&#13;
&#13;
<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=177_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on September 04, 2013 13:16:41_

<i>(No comment was entered for this change.)</i>

**Status:** Accepted  
  **Owner:** martin.grotzke  
  **Labels:** -Type-Defect Type-Enhancement

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on November 26, 2013 12:52:38_

Fixed, will be included in the next release.

**Status:** Fixed  
  **Labels:** Milestone-1.7.0
