### ISSUE TITLE
[Solved]Begin event threw error java.lang.NoClassDefFoundError: com/couchbase/client/CouchbaseClient

### ISSUE THREAD

**Issue by google-code-exporter** [magro/memcached-session-manager#221]
_From [l173246...@gmail.com](https://code.google.com/u/109604547700888640590/) on October 20, 2013 12:08:49_

This problew was in  memcached-session-mamager-1.6.5 
next lines are error codes
SEVERE: Begin event threw error
java.lang.NoClassDefFoundError: com/couchbase/client/CouchbaseClient
         at
de.javakaffee.web.msm.MemcachedBackupSessionManager.(Native
Method)
         at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown
Source)
         at
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
         at java.lang.reflect.Constructor.newInstance(Unknown Source)
         at java.lang.Class.newInstance0(Unknown Source)

and  I have added  this jar file ,and my problem solved 
couchbase-client-1.1.4.jar
(<a href="http://files.couchbase.com/maven2/couchbase/couchbase-client/1.1.4/couchbase-client-1.1.4.jar" rel="nofollow">http://files.couchbase.com/maven2/couchbase/couchbase-client/1.1.4/couchbase-client-1.1.4.jar</a>)

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=180_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on October 20, 2013 03:27:55_

So finally you followed the setup instructions ;-)

**Status:** Invalid
