### ISSUE TITLE
SOS!

### ISSUE THREAD

**Issue by google-code-exporter** [magro/memcached-session-manager#232]
_From [q9133...@gmail.com](https://code.google.com/u/105379188071147499238/) on December 26, 2013 03:27:51_

why? Could not load session with id 5280802928EC4B98D96856D3818C1BBF-n1 from memcached.
?

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=191_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on December 25, 2013 23:06:05_

There should be some more information in the logs, you can also try to make logging more verbose as described in the the documentation.

**Comment by google-code-exporter** [comment]
_From [q9133...@gmail.com](https://code.google.com/u/105379188071147499238/) on December 26, 2013 22:46:32_

Could not get backup validityInfo or backup session for sessionId 1BE1F0C5EEA9467B9310B2A2FC54F687-n2
java.lang.IllegalArgumentException: No node found for key bak:validity:1BE1F0C5EEA9467B9310B2A2FC54F687-n2 (nodeId: null, known nodeIds: [n1, n2])
	at de.javakaffee.web.msm.SuffixBasedNodeLocator.getPrimary(SuffixBasedNodeLocator.java:101)
	at net.spy.memcached.MemcachedConnection.addOperation(MemcachedConnection.java:690)
	at net.spy.memcached.MemcachedClient.addOp(MemcachedClient.java:453)
	at net.spy.memcached.MemcachedClient.asyncGet(MemcachedClient.java:1017)
	at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1178)
	at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1200)
	at de.javakaffee.web.msm.LockingStrategy.loadSessionValidityInfoForValidityKey(LockingStrategy.java:331)
	at de.javakaffee.web.msm.LockingStrategy.loadBackupSessionValidityInfo(LockingStrategy.java:339)
	at de.javakaffee.web.msm.MemcachedSessionService.loadBackupSession(MemcachedSessionService.java:874)
	at de.javakaffee.web.msm.MemcachedSessionService.loadBackupSession(MemcachedSessionService.java:861)
	at de.javakaffee.web.msm.MemcachedSessionService.changeSessionIdOnMemcachedFailover(MemcachedSessionService.java:822)
	at de.javakaffee.web.msm.SessionTrackerValve.changeRequestedSessionId(SessionTrackerValve.java:225)
	at de.javakaffee.web.msm.SessionTrackerValve.invoke(SessionTrackerValve.java:148)
	at org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:95)
	at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.process(SecurityContextEstablishmentValve.java:126)
	at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.invoke(SecurityContextEstablishmentValve.java:70)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:158)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:330)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:905)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:592)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:2036)
	at java.lang.Thread.run(Thread.java:662)

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on December 27, 2013 00:52:39_

According to the provided information this could be a duplicate of <a title=" Could not store secondary backup of session " href="/p/memcached-session-manager/issues/detail?id=157">issue #157</a>. Please check this issue for pointers.

**Status:** Duplicate  
  **Mergedinto:** 157
