### ISSUE TITLE
NoSuchMethodError in KryoTranscoderFactory on Tomcat 8

### ISSUE THREAD

**Issue by google-code-exporter** [magro/memcached-session-manager#235]
_From [clecl...@cloudbees.com](https://code.google.com/u/114052721732429955028/) on February 01, 2014 19:54:59_

KryoTranscoderFactory still relies on Container.getLoader()  and has not yet been updated to MemcachedSessionService.SessionManager.getContainerClassLoader(), see (1).

There is the same problem for javolution-serializer.

I'm preparing a pull-request.

{{{
01-Feb-2014 18:26:32.664 INFO [localhost-startStop-1] de.javakaffee.web.msm.MemcachedSessionService.createTranscoderFactory Creating transcoder factory de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory
01-Feb-2014 18:26:32.666 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Error manager.start()
 org.apache.catalina.LifecycleException: Failed to start component [de.javakaffee.web.msm.MemcachedBackupSessionManager[]]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
    at ...
Caused by: java.lang.NoSuchMethodError: org.apache.catalina.Container.getLoader()Lorg/apache/catalina/Loader;
    at de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory.createTranscoder(KryoTranscoderFactory.java:48)
    at de.javakaffee.web.msm.MemcachedSessionService.createTranscoderService(MemcachedSessionService.java:484)
    at de.javakaffee.web.msm.MemcachedSessionService.startInternal(MemcachedSessionService.java:439)
    at de.javakaffee.web.msm.MemcachedBackupSessionManager.startInternal(MemcachedBackupSessionManager.java:505)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    ... 12 more
}}}

(1) <a href="https://github.com/magro/memcached-session-manager/commit/6e4b6dbc1a7b5a2e685148052d2fe545ae9b2eae#diff-01a92d53fb42d90695ffa766716106b3L204" rel="nofollow">https://github.com/magro/memcached-session-manager/commit/6e4b6dbc1a7b5a2e685148052d2fe545ae9b2eae#diff-01a92d53fb42d90695ffa766716106b3L204</a>

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=194_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on February 01, 2014 16:30:24_

Thanks for reporting and the pull request!

**Status:** Fixed  
  **Labels:** Milestone-1.8.1
