### ISSUE TITLE
 kryo-users › com.esotericsoftware.kryo.SerializationException: Buffer limit exceeded writing object of type:

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#240]
_From [yoga.und...@gmail.com](https://code.google.com/u/111652832360445102669/) on March 03, 2014 23:55:41_

<b>What steps will reproduce the problem?</b>
1. msm + kryo + legacy spring mvc application&#13;
2. Override the default max buffer size to 10 MB(-Dmsm.kryo.buffersize.max=10240000)&#13;
3. &lt;Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"&#13;
            sticky="false"&#13;
            memcachedNodes="n1:host1:11211,n2:host2:11211"&#13;
            failoverNodes="n1"&#13;
            lockingMode="all"&#13;
            requestUriIgnorePattern=".*\.(png|gif|jpg|css|js|ico)$"&#13;
            sessionBackupAsync="false"&#13;
            sessionBackupTimeout="100"&#13;
            copyCollectionsForSerialization="true"&#13;
            transcoderFactoryClass="de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory"&#13;
    /&gt;&#13;
&#13;
<b>What is the expected output? What do you see instead?</b>
Application should work as it did work currently with HttpSession to store session info. &#13;
But it's failing due to Buffer limit exceeded writing object of type:&#13;
&#13;
<b>What version of the product are you using? On what operating system?</b>
spymemcached-2.10.2.jar&#13;
memcached-session-manager-tc6-1.8.1.jar&#13;
memcached-session-manager-1.8.1.jar&#13;
reflectasm-1.01.jar&#13;
msm-kryo-serializer-1.8.1.jar&#13;
minlog-1.2.jar&#13;
kryo-serializers-0.11.jar&#13;
kryo-1.04.jar&#13;
asm-3.3.1.jar&#13;
&#13;
<b>Please provide any additional information below.</b>
We are integrating memcached session manager (msm) + kryo with our legacy applications, as part of that testing getting following error. I don't have permission to change any code in the legacy applications. So I have to transparently migrate an application from HttpSession  to Memcached.&#13;
&#13;
Feb 28, 2014 5:26:36 PM de.javakaffee.web.msm.BackupSessionService backupSession&#13;
INFO: Could not store session BA46520D8EA570DEC2A6674340FF22C7-n2.tomcat1 in memcached.&#13;
java.util.concurrent.ExecutionException: com.esotericsoftware.kryo.SerializationException: Buffer limit exceeded serializing object of type: java.util.concurrent.ConcurrentHashMap&#13;
	at de.javakaffee.web.msm.BackupSessionService$SynchronousExecutorService.submit(BackupSessionService.java:348)&#13;
	at de.javakaffee.web.msm.BackupSessionService.backupSession(BackupSessionService.java:205)&#13;
	at de.javakaffee.web.msm.MemcachedSessionService.backupSession(MemcachedSessionService.java:1040)&#13;
	at de.javakaffee.web.msm.RequestTrackingHostValve.backupSession(RequestTrackingHostValve.java:230)&#13;
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:159)&#13;
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)&#13;
	at com.etrade.neo.tomcat.accessvalve.NEOAccessLogValve.invoke(NEOAccessLogValve.java:572)&#13;
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)&#13;
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)&#13;
	at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)&#13;
	at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291)&#13;
	at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:769)&#13;
	at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:698)&#13;
	at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:891)&#13;
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)&#13;
	at java.lang.Thread.run(Thread.java:662)&#13;
Caused by: com.esotericsoftware.kryo.SerializationException: Buffer limit exceeded serializing object of type: java.util.concurrent.ConcurrentHashMap&#13;
	at com.esotericsoftware.kryo.ObjectBuffer.writeObject(ObjectBuffer.java:256)&#13;
	at de.javakaffee.web.msm.serializer.kryo.KryoTranscoder.serializeAttributes(KryoTranscoder.java:303)&#13;
	at de.javakaffee.web.msm.TranscoderService.serializeAttributes(TranscoderService.java:155)&#13;
	at de.javakaffee.web.msm.BackupSessionTask.serializeAttributes(BackupSessionTask.java:176)&#13;
	at de.javakaffee.web.msm.BackupSessionTask.call(BackupSessionTask.java:110)&#13;
	at de.javakaffee.web.msm.BackupSessionTask.call(BackupSessionTask.java:51)&#13;
	at de.javakaffee.web.msm.BackupSessionService$SynchronousExecutorService.submit(BackupSessionService.java:346)&#13;
	... 15 more&#13;
Caused by: com.esotericsoftware.kryo.SerializationException: Buffer limit exceeded writing object of type: java.util.concurrent.ConcurrentHashMap&#13;
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:523)&#13;
	at com.esotericsoftware.kryo.ObjectBuffer.writeObject(ObjectBuffer.java:251)&#13;
	... 21 more&#13;
Caused by: com.esotericsoftware.kryo.SerializationException: Buffer limit exceeded writing object of type: org.springframework.web.context.request.DestructionCallbackBindingListener&#13;
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:492)&#13;
	at com.esotericsoftware.kryo.serialize.MapSerializer.writeObjectData(MapSerializer.java:104)&#13;
	at de.javakaffee.kryoserializers.CopyForIterateMapSerializer.writeObjectData(CopyForIterateMapSerializer.java:56)&#13;
	at com.esotericsoftware.kryo.Serializer.writeObject(Serializer.java:43)&#13;
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:520)&#13;
	... 22 more&#13;
Caused by: com.esotericsoftware.kryo.SerializationException: Buffer limit exceeded writing object of type: org.apache.cxf.bus.spring.Jsr250BeanPostProcessor&#13;
Serialization trace:&#13;
beanPostProcessors (org.springframework.beans.factory.support.DisposableBeanAdapter)&#13;
destructionCallback (org.springframework.web.context.request.DestructionCallbackBindingListener)&#13;
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:492)&#13;
	at com.esotericsoftware.kryo.serialize.CollectionSerializer.writeObjectData(CollectionSerializer.java:86)&#13;
	at de.javakaffee.kryoserializers.CopyForIterateCollectionSerializer.writeObjectData(CopyForIterateCollectionSerializer.java:46)&#13;
	at com.esotericsoftware.kryo.serialize.FieldSerializer.writeObjectData(FieldSerializer.java:175)&#13;
	at com.esotericsoftware.kryo.serialize.ReferenceFieldSerializer.writeObjectData(ReferenceFieldSerializer.java:52)&#13;
	at com.esotericsoftware.kryo.serialize.FieldSerializer.writeObjectData(FieldSerializer.java:175)&#13;
	at com.esotericsoftware.kryo.serialize.ReferenceFieldSerializer.writeObjectData(ReferenceFieldSerializer.java:52)&#13;
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:489)&#13;
	... 26 more&#13;
Caused by: com.esotericsoftware.kryo.SerializationException: Buffer limit exceeded writing object of type: java.lang.Package&#13;
Serialization trace:&#13;
packages (org.apache.catalina.loader.WebappClassLoader)&#13;
beanClassLoader (org.springframework.beans.factory.support.DefaultListableBeanFactory)&#13;
beanFactory (org.springframework.context.event.SimpleApplicationEventMulticaster)&#13;
applicationEventMulticaster (com.etrade.neo.spring.cont...

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=199_

**Comment by google-code-exporter** [comment]
_From [yoga.und...@gmail.com](https://code.google.com/u/111652832360445102669/) on March 03, 2014 15:01:21_

OS : Linux x86_64 x86_64 x86_64 GNU/Linux

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on March 06, 2014 04:45:44_

I'd say you're serializing the whole spring ApplicationContext. Or might there be another reason for such big sessions?

**Comment by google-code-exporter** [comment]
_From [yoga.und...@gmail.com](https://code.google.com/u/111652832360445102669/) on March 06, 2014 08:42:14_

The same application + Coherence Web Session+ Kryo and same application + Hazelcast Wen Session + Kryo doesn't have this issue. Also we measured the max size of the session in those two web sessions framework, max session size is 30 KB.

**Comment by google-code-exporter** [comment]
_From [yoga.und...@gmail.com](https://code.google.com/u/111652832360445102669/) on March 27, 2014 11:32:53_

msm +  Java Serialization + Spring MVC, going good, but I see one or two issue while serializing SPRING SECURITY CONTEXT. Looking into it now. It seems like one of our custom authentication class not implemented Serializable, causing this issue, let me updated once I'm done with testing.

Cannot serialize session attribute SPRING_SECURITY_CONTEXT for session

Thanks
Yoga

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on March 27, 2014 13:12:25_

For this one, can you provide a simple spring app that allows to reproduce the issue that I could use to debug this?

**Comment by google-code-exporter** [comment]
_From [yoga.und...@gmail.com](https://code.google.com/u/111652832360445102669/) on March 30, 2014 21:33:48_

Hi Martin,

Please find attached  Spring Mvc , where I'm still getting lot below exception, when I remove implements Serializable from User class. This is same happening in our legacy spring mvc based application. I'm adding Serializable interface to classes which are failing one by one, but still the list keep on growing.

Mar 28, 2014 5:32:56 PM de.javakaffee.web.msm.JavaSerializationTranscoder writeAttributes
WARNING: Cannot serialize session attribute org.springframework.web.context.request.ServletRequestAttributes.DESTRUCTION_CALLBACK.scopedTarget.userProfile for session F26FF1B9DFDFE7C3EB1110F11449A5F3-n2.tomcat1
java.io.NotSerializableException: com.dev.spring.context.JaxWsClientProxy
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1164)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1518)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1483)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1400)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1158)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1518)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1483)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1400)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1158)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1518)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1483)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1400)

**Attachment:** [springmvc-ser.zip](http://code.google.com/p/memcached-session-manager/issues/detail?id=199#hc6)

**Comment by google-code-exporter** [comment]
_From [yoga.und...@gmail.com](https://code.google.com/u/111652832360445102669/) on March 31, 2014 09:46:11_

Hi Martin,

Any suggestion/direction to avoid the above exception gracefully, because our legacy application has tons of classes without Serilizable interface implementation.

Thanks
Yoga
