### ISSUE TITLE
memcached-session-manager tc7 1.7.0 is not compatible with tomcat catalina 7.0.25 and below

### ISSUE THREAD

**Issue by google-code-exporter** [magro/memcached-session-manager#241]
_From [VISH.THE...@gmail.com](https://code.google.com/u/100648434526029074543/) on March 04, 2014 15:00:33_

<b>What steps will reproduce the problem?</b>
1.upgraded required msm jars from version 1.6.5 to 1.7.0&#13;
2.Using Tomcat 7.0.23&#13;
&#13;
<b>What is the expected output? What do you see instead?</b>
Ideally session replication should have worked&#13;
&#13;
<b>What version of the product are you using? On what operating system?</b>
I am as of now using version 1.6.5 with linux fedora operating system&#13;
&#13;
<b>Please provide any additional information below.</b>
&#13;
Observed error:&#13;
Caused by: java.lang.NoClassDefFoundError: org/apache/catalina/util/SessionConfig&#13;
	at de.javakaffee.web.msm.MemcachedBackupSessionManager.getSessionCookieName(MemcachedBackupSessionManager.java:829)&#13;
	at de.javakaffee.web.msm.MemcachedSessionService.startInternal(MemcachedSessionService.java:416)&#13;
	at de.javakaffee.web.msm.MemcachedBackupSessionManager.startInternal(MemcachedBackupSessionManager.java:524)&#13;
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:148)&#13;
	... 31 more&#13;
&#13;
&#13;
Reason found:  &#13;
&#13;
org/apache/catalina/util/SessionConfig was introduced in tomcat-catalina 7.0.26

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=200_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on March 04, 2014 14:38:03_

I suggest to upgrade to the latest tomcat 7 release.

**Comment by google-code-exporter** [comment]
_From [VISH.THE...@gmail.com](https://code.google.com/u/100648434526029074543/) on March 05, 2014 08:49:31_

Martin, the problem is, its too huge a change, i know your suggestion is valid, but the change might have high impact on our systems. Still, will try to achieve that. 

Just a suggestion, please add this somewhere in your docs, so that people may know, before trying to upgrade.

Thanks,
Vishal Meghani

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on March 06, 2014 04:41:41_

Hmm, do you have a suggestion where to add this hint?

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on March 06, 2014 04:43:09_

Btw, you could also submit a pull request that adds some reflection to support also older versions of tomcat7.

**Comment by google-code-exporter** [comment]
_From [VISH.THE...@gmail.com](https://code.google.com/u/100648434526029074543/) on March 06, 2014 06:11:02_

Martin, i think setupAndConfiguration's Configure tomcat should be the right place to add this.

Its a nyc idea, to submit a pull request and use reflection, will do that if necessary. :)

Thanks for all your help.

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on March 27, 2014 00:56:19_

Docs are updated.

**Status:** Done
