### ISSUE TITLE
No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread.

### ISSUE THREAD

**Issue by google-code-exporter** [magro/memcached-session-manager#245]
_From [yoga.und...@gmail.com](https://code.google.com/u/111652832360445102669/) on March 25, 2014 22:57:42_

<b>What steps will reproduce the problem?</b>
1. Enable msm logger as per document&#13;
&#13;
2. Add following line in cataclina.sh&#13;
 CATALINA_OPTS="$CATALINA_OPTS -Dnet.spy.log.LoggerImpl=net.spy.memcached.compat.log.SunLogger" &#13;
&#13;
3. Add following lines in CATALINA_HOME/conf/logging.properties&#13;
de.javakaffee.web.msm.level=FINE&#13;
# A handler's log level threshold can be set using SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST or ALL&#13;
net.spy.memcached.level = FINE&#13;
# To make only the MemcachedConnection less verbose:&#13;
net.spy.memcached.MemcachedConnection.level = FINE&#13;
&#13;
<b>What is the expected output? What do you see instead?</b>
User session should be stored in Memcached server, instead I see "Could not store session 9B5C8BF8A55A37A93785F86B75DF2D0A-n2 in memcached."&#13;
&#13;
<b>What version of the product are you using? On what operating system?</b>
spymemcached-2.10.2.jar&#13;
memcached-session-manager-tc6-1.8.1.jar&#13;
memcached-session-manager-1.8.1.jar&#13;
tomcat-6.0.39&#13;
&#13;
<b>Please provide any additional information below.</b>
&#13;
Error Stack trace. If I disable the logger this issue goes away.&#13;
&#13;
&#13;
INFO: Could not store session 9B5C8BF8A55A37A93785F86B75DF2D0A-n2 in memcached.&#13;
java.util.concurrent.ExecutionException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.sessUser': Scope 'session' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.&#13;
        at de.javakaffee.web.msm.BackupSessionService$SynchronousExecutorService.submit(BackupSessionService.java:348)&#13;
        at de.javakaffee.web.msm.BackupSessionService.backupSession(BackupSessionService.java:205)&#13;
        at de.javakaffee.web.msm.MemcachedSessionService.backupSession(MemcachedSessionService.java:1040)&#13;
        at de.javakaffee.web.msm.RequestTrackingHostValve.backupSession(RequestTrackingHostValve.java:230)&#13;
        at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:159)&#13;
        at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:124)&#13;
        at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:124)&#13;
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)&#13;
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)&#13;
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)&#13;
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)&#13;
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)&#13;
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)&#13;
        at java.lang.Thread.run(Thread.java:722)&#13;
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.sessUser': Scope 'session' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.&#13;
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:342)&#13;
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)&#13;
        at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:33)&#13;
        at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.getTarget(Cglib2AopProxy.java:654)&#13;
        at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:605)&#13;
        at com.etrade.ser.issue.controller.User$$EnhancerByCGLIB$$7342260b.toString(&lt;generated&gt;)&#13;
        at java.lang.String.valueOf(String.java:2902)&#13;
        at java.lang.StringBuilder.append(StringBuilder.java:128)&#13;
        at de.javakaffee.web.msm.JavaSerializationTranscoder.writeAttributes(JavaSerializationTranscoder.java:140)&#13;
        at de.javakaffee.web.msm.JavaSerializationTranscoder.serializeAttributes(JavaSerializationTranscoder.java:99)&#13;
        at de.javakaffee.web.msm.TranscoderService.serializeAttributes(TranscoderService.java:155)&#13;
        at de.javakaffee.web.msm.BackupSessionTask.serializeAttributes(BackupSessionTask.java:176)&#13;
        at de.javakaffee.web.msm.BackupSessionTask.call(BackupSessionTask.java:110)&#13;
        at de.javakaffee.web.msm.BackupSessionTask.call(BackupSessionTask.java:51)&#13;
&#13;
        at de.javakaffee.web.msm.BackupSessionTask.call(BackupSessionTask.java:110)&#13;
        at de.javakaffee.web.msm.BackupSessionTask.call(BackupSessionTask.java:51)&#13;
        at de.javakaffee.web.msm.BackupSessionService$SynchronousExecutorService.submit(BackupSessionService.java:346)&#13;
        ... 13 more&#13;
Caused by: java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.&#13;
        at org.springframework.web.context.request.RequestContextHolder.currentRequestAttributes(RequestContextHolder.java:131)&#13;
        at org.springframework.web.context.request.SessionScope.get(SessionScope.java:90)&#13;
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:328)&#13;
        ... 27 more&#13;
&#13;
Mar 25, 2014 2:26:32 PM net.spy.memcached.MemcachedConnection addOperation&#13;

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=204_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on March 27, 2014 00:41:35_

Can you provide a simple spring app with a session scoped bean that I could use to debug this?

**Comment by google-code-exporter** [comment]
_From [yoga.und...@gmail.com](https://code.google.com/u/111652832360445102669/) on March 27, 2014 11:26:12_

Hi Martin,

No more I getting this issue, please close this issue.

It was happening due to an error while getting a proxy instance in my code, after I correct the error in the code, now I'm able to see the msm logs are getting logged.

Thanks
Yoga

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on March 27, 2014 13:10:56_

Ok

**Status:** Invalid
