### ISSUE TITLE
Add async support for tomcat8

### ISSUE THREAD

**Issue by google-code-exporter** [magro/memcached-session-manager#249]
_From [Kartik...@gmail.com](https://code.google.com/u/103826724080458750160/) on June 01, 2014 11:48:03_

<b>What steps will reproduce the problem?</b>
&#13;
1.On adding memcached session manager in tomcat8 or 7, long polling stopped working. Without memcached it works perfectly fine.&#13;
&#13;
2.I am getting following errors in tomcat logs:&#13;
java.lang.IllegalStateException: Not supported.&#13;
	at org.apache.catalina.connector.Request.startAsync(Request.java:1604) ~[catalina.jar:8.0.5]&#13;
	at org.apache.catalina.connector.RequestFacade.startAsync(RequestFacade.java:1037) ~[catalina.jar:8.0.5]&#13;
	at org.atmosphere.cpr.AtmosphereRequest.startAsync(AtmosphereRequest.java:692) ~[AtmosphereRequest.class:2.1.4]&#13;
	at org.atmosphere.container.Servlet30CometSupport.suspend(Servlet30CometSupport.java:93) ~[Servlet30CometSupport.class:2.1.4]&#13;
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:68) ~[Servlet30CometSupport.class:2.1.4]&#13;
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1801) ~[AtmosphereFramework.class:2.1.4]&#13;
	at org.atmosphere.cpr.AtmosphereServlet.doPost(AtmosphereServlet.java:210) [AtmosphereServlet.class:2.1.4]&#13;
	at org.atmosphere.cpr.AtmosphereServlet.doGet(AtmosphereServlet.java:196) [AtmosphereServlet.class:2.1.4]&#13;
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618) [servlet-api.jar:na]&#13;
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:na]&#13;
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:301) [catalina.jar:8.0.5]&#13;
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.5]&#13;
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.5]&#13;
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.5]&#13;
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.5]&#13;
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.5]&#13;
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.5]&#13;
	at de.javakaffee.web.msm.RequestTrackingContextValve.invoke(RequestTrackingContextValve.java:99) [memcached-session-manager-1.8.1.jar:na]&#13;
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503) [catalina.jar:8.0.5]&#13;
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:136) [catalina.jar:8.0.5]&#13;
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:124) [memcached-session-manager-1.8.1.jar:na]&#13;
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:124) [memcached-session-manager-1.8.1.jar:na]&#13;
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:124) [memcached-session-manager-1.8.1.jar:na]&#13;
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:124) [memcached-session-manager-1.8.1.jar:na]&#13;
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:124) [memcached-session-manager-1.8.1.jar:na]&#13;
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:156) [memcached-session-manager-1.8.1.jar:na]&#13;
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:124) [memcached-session-manager-1.8.1.jar:na]&#13;
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:74) [catalina.jar:8.0.5]&#13;
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.5]&#13;
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.5]&#13;
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:526) [catalina.jar:8.0.5]&#13;
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1017) [tomcat-coyote.jar:8.0.5]&#13;
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:652) [tomcat-coyote.jar:8.0.5]&#13;
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222) [tomcat-coyote.jar:8.0.5]&#13;
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1575) [tomcat-coyote.jar:8.0.5]&#13;
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1533) [tomcat-coyote.jar:8.0.5]&#13;
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_45]&#13;
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_45]&#13;
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]&#13;
&#13;
&#13;
<b>What version of the product are you using? On what operating system?</b>
memcached-session-manager-1.8.1 on ubuntu, this issue is also coming on windows machine&#13;
&#13;
<b>Please provide any additional information below.</b>
I am using atmosphere framework for long-polling and websockets. websockets works fine, but long polling fails.

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=208_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on June 01, 2014 04:23:44_

Async should be basically supported, at least with reading from the session, see <a title="Tomcat7: check/implement support of async/comet requests" class="closed_ref" href="/p/memcached-session-manager/issues/detail?id=75"> issue #75 </a> and this commit: <a href="https://github.com/magro/memcached-session-manager/commit/5a6b0b6d761dff086010d2d0ef0bdf29c3f418d9" rel="nofollow">https://github.com/magro/memcached-session-manager/commit/5a6b0b6d761dff086010d2d0ef0bdf29c3f418d9</a>&#13;
&#13;
Have you tried using tomcat7? Perhaps this is missing for tomcat8.&#13;
&#13;
Cheers,&#13;
Martin&#13;

**Comment by google-code-exporter** [comment]
_From [Kartik...@gmail.com](https://code.google.com/u/103826724080458750160/) on June 01, 2014 23:23:43_

Hi Martin,

Thank you for quick reply. Yes, it is working perfectly fine with tomcat7. Please push this change for tomcat8 also.

Thank you for looking on this.

Regards,
Kartik

**Comment by google-code-exporter** [comment]
_From [Kartik...@gmail.com](https://code.google.com/u/103826724080458750160/) on June 04, 2014 00:05:36_

Hi Martin,

Any idea of timeline by when we can see this update in tc8?

Regards,
Kartik

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on June 04, 2014 16:26:23_

Hi Kartik,

I should find time for this next week.

Cheers,
Martin

**Comment by google-code-exporter** [comment]
_From [Kartik...@gmail.com](https://code.google.com/u/103826724080458750160/) on June 15, 2014 00:59:59_

Hi, any updates on this? Sorry to bug you again about this. As I want to go for tomcat8.

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on June 15, 2014 15:35:27_

It's fixed now, I just released msm 1.8.2 containing this fix.

**Summary:** Add async support for tomcat8  <span class="oldvalue"> (was: long polling stopped working) </span>  
  **Status:** Fixed  
  **Labels:** Milestone-1.8.2

**Comment by google-code-exporter** [comment]
_From [Kartik...@gmail.com](https://code.google.com/u/103826724080458750160/) on June 18, 2014 22:28:10_

Its working fine. Thank you for looking into this.
