### ISSUE TITLE
Add support to store serialized data as a string to work around loss of type information after Couchbase failover

### ISSUE THREAD

**Issue by google-code-exporter** [magro/memcached-session-manager#255]
_From [andre.va...@spritzinc.com](https://code.google.com/u/116764051586867443170/) on November 04, 2014 20:26:09_

After a couchbase node failover, sessions that are pulled from a replica lose their type information.  Instead of returning a byte array, the CouchBase client returns a String, resulting in a ClassCastException:

Reproduction Steps
1.  On a Couchbase cluster, configure a bucket for Tomcat sessions with replication enabled.
2.  Populate the bucket with some sessions.
3.  Bring down the node containing your target session.
4.  Make a request to the Tomcat server with your session.

Either use a single session, and a new / empty bucket so you can tell which server is the primary for your session, or a load test with several session.

Expected output:
The Tomcat server restores the last known state of the session

What do you see instead?
The following exception and Stack Trace:
de.javakaffee.web.msm.MemcachedSessionService
loadFromMemcached
WARNING: Could not load session with id 2CAF3AD14FCB9B4F92A9E0684AB49D28
from memcached.
java.lang.ClassCastException: java.lang.String cannot be cast to [B
	at de.javakaffee.web.msm.LockingStrategy.loadSessionValidityInfoForValidityKey(LockingStrategy.java:333)
	at de.javakaffee.web.msm.LockingStrategy.loadSessionValidityInfo(LockingStrategy.java:328)
	at de.javakaffee.web.msm.LockingStrategy.onAfterLoadFromMemcached(LockingStrategy.java:363)
	at de.javakaffee.web.msm.MemcachedSessionService.loadFromMemcached(MemcachedSessionService.java:1106)
	at de.javakaffee.web.msm.MemcachedSessionService.findSession(MemcachedSessionService.java:585)
	at de.javakaffee.web.msm.MemcachedBackupSessionManager.findSession(MemcachedBackupSessionManager.java:216)
	at org.apache.catalina.connector.Request.doGetSession(Request.java:2913)
	at org.apache.catalina.connector.Request.getSession(Request.java:2310)
	at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:897)
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:229)
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:229)
	...

<b>What version of the product are you using? On what operating system?</b>
Amazon Linux 2014.09&#13;
Tomcat 7.0.55&#13;
memcached-session-manager-1.8.1.&#13;
Couchbase Servers Version: 3.0.0 Community Edition (build-1209)&#13;
Couchbase Client: 1.4.5&#13;
&#13;
Please provide any additional information below:&#13;
&#13;
On testing with a standalone Java program, it looks like values that are stored as Strings do read back correctly after a failover.  If it was possible for the transcoder to use a base64 encoded string instead of a byte array, it should work around the problem.&#13;

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=216_

**Comment by google-code-exporter** [comment]
_From [andre.va...@spritzinc.com](https://code.google.com/u/116764051586867443170/) on November 04, 2014 15:31:30_

This was caused by Couchbase bug MB-12328 (<a href="http://www.couchbase.com/issues/browse/MB-12328" rel="nofollow">http://www.couchbase.com/issues/browse/MB-12328</a>)&#13;
&#13;
As that issue has been fixed in version 3.0.1, working around the problem with a String is no longer necessary.  I think this issue can be closed.

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on November 05, 2014 14:12:24_

Ok, closing.

**Status:** WontFix
