### ISSUE TITLE
Add really helpful log message to diagnose serialization problems.

### ISSUE THREAD

**Issue by google-code-exporter** [magro/memcached-session-manager#258]
_From [tjordahl@gmail.com](https://code.google.com/u/tjordahl@gmail.com/) on November 19, 2014 23:36:59_

Please add a key log message to help diagnose problems when MSM will silently fail to store sessions.

1. Put things in your session that can't be serialized.
2. Enable MSM and watch it not work silently.

<b>What is the expected output? What do you see instead?</b>
I see this:FINE: Starting for session id 023D38178F52D22676A2EC0C825CB371-n0.ip-10-1-49-49&#13;
Nov 19, 2014 1:04:32 PM de.javakaffee.web.msm.BackupSessionTask call&#13;
FINE: Starting for session id 023D38178F52D22676A2EC0C825CB371-n0.ip-10-1-49-49&#13;
Nov 19, 2014 1:04:32 PM de.javakaffee.web.msm.BackupSessionTask call&#13;
FINE: Starting for session id 023D38178F52D22676A2EC0C825CB371-n0.ip-10-1-49-49&#13;
&#13;
I need to see this:&#13;
Nov 19, 2014 2:25:36 PM de.javakaffee.web.msm.BackupSessionTask call&#13;
FINE: Starting for session id 11864A559B4296BB88B0B37EB1A0157B-n0.ip-10-1-49-49&#13;
Nov 19, 2014 2:25:36 PM de.javakaffee.web.msm.BackupSessionTask call&#13;
FINE: FAILED for session id 11864A559B4296BB88B0B37EB1A0157B-n0.ip-10-1-49-49&#13;
com.esotericsoftware.kryo.SerializationException: Unable to serialize object of type: java.util.concurrent.ConcurrentHashMap&#13;
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:524)&#13;
        at com.esotericsoftware.kryo.ObjectBuffer.writeObject(ObjectBuffer.java:251)&#13;
&#13;
[NOTE: the ConcurrentHashMap isn't the problem, I have a hibernate lazy object in the map that can't be serialized]&#13;
&#13;
Using the latest git source (1.8.4-SNAPSHOT) from git on CentOS as of 19-Nov-2014.&#13;
&#13;
Please add the following (or something similar) to BackupSessionTask.java on or around line 150.  Patch file attached.&#13;
&#13;
--- a/core/src/main/java/de/javakaffee/web/msm/BackupSessionTask.java&#13;
+++ b/core/src/main/java/de/javakaffee/web/msm/BackupSessionTask.java&#13;
@@ -148,7 +148,11 @@ public class BackupSessionTask implements Callable&lt;BackupResult&gt; {&#13;
 &#13;
             return result;&#13;
 &#13;
-        } finally {&#13;
+        } catch (Exception e) {&#13;
+            _log.warn("FAILED for session id " + _session.getId(), e);&#13;
+            throw e;&#13;
+        }&#13;
+        finally {&#13;
             _session.setBackupRunning( false );&#13;
             releaseLock();&#13;
         }&#13;
&#13;
&#13;
&#13;

**Attachment:** [BackupSessionTask.patch](http://code.google.com/p/memcached-session-manager/issues/detail?id=219)

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=219_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on November 19, 2014 15:36:34_

Good catch! Can you submit a pull request please?

**Comment by google-code-exporter** [comment]
_From [tjordahl@gmail.com](https://code.google.com/u/tjordahl@gmail.com/) on November 20, 2014 08:01:24_

Sent Pull request:
<a href="https://github.com/magro/memcached-session-manager/pull/42" rel="nofollow">https://github.com/magro/memcached-session-manager/pull/42</a>&#13;

**Comment by google-code-exporter** [comment]
_From [tjordahl@gmail.com](https://code.google.com/u/tjordahl@gmail.com/) on November 20, 2014 08:01:31_

Here ya go
<a href="https://github.com/magro/memcached-session-manager/pull/42" rel="nofollow">https://github.com/magro/memcached-session-manager/pull/42</a>

Tom Jordahl

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on November 20, 2014 11:03:36_

Merged, thanks!

**Status:** Fixed  
  **Labels:** Milestone-1.8.4
