### ISSUE TITLE
ClassNotFoundException when Class in jar

### ISSUE THREAD

**Issue by friddle** [magro/memcached-session-manager#271]
Error Info:     
 

Caused by: java.lang.ClassNotFoundException: com.talkweb.ybb.core.model.user.UserExtInfo
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1722)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1573)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:274)
        at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:447)
        ... 27 more

We packed the Class:UserExt to WEB-INF/lib/xxx.jar files.
is it a bug? or I should do something others to fix the problem?

**Comment by friddle** [comment]
I find the Same Issue, So sorry.
