### ISSUE TITLE
Javalution serializer 1.8.3 is not compatible with Apache Tomcat 8

### ISSUE THREAD

**Issue by huksley** [magro/memcached-session-manager#276]
Hello!

I am trying to use MSM +Javalution in Apache Tomcat 8.0.26
Following JARs:
javolution-5.4.5.jar
memcached-session-manager-1.8.3.jar
memcached-session-manager-tc8-1.8.3.jar
msm-javolution-serializer-1.8.3.jar
spymemcached-2.7.3.jar

I am getting following error:

08-Oct-2015 09:25:41.461 INFO [localhost-startStop-1] de.javakaffee.web.msm.MemcachedSessionService.createTranscoderFactory Creating transcoder factory de.javakaffee.web.msm.serializer.javolution.JavolutionTranscoderFactory
08-Oct-2015 09:25:41.467 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal The session manager failed to start
 org.apache.catalina.LifecycleException: Failed to start component [de.javakaffee.web.msm.MemcachedBackupSessionManager[]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5184)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1101)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1786)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.apache.catalina.Container.getLoader()Lorg/apache/catalina/Loader;
        at de.javakaffee.web.msm.serializer.javolution.JavolutionTranscoder.<init>(JavolutionTranscoder.java:86)
        at de.javakaffee.web.msm.serializer.javolution.JavolutionTranscoderFactory.getTranscoder(JavolutionTranscoderFactory.java:56)
        at de.javakaffee.web.msm.serializer.javolution.JavolutionTranscoderFactory.createTranscoder(JavolutionTranscoderFactory.java:43)
        at de.javakaffee.web.msm.MemcachedSessionService.createTranscoderService(MemcachedSessionService.java:484)
        at de.javakaffee.web.msm.MemcachedSessionService.startInternal(MemcachedSessionService.java:439)
        at de.javakaffee.web.msm.MemcachedBackupSessionManager.startInternal(MemcachedBackupSessionManager.java:518)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        ... 12 more

**Comment by magro** [comment]
Thanks for reporting this, @huksley! Would you like to submit a pull request? This would speed up fixing this :-)

**Comment by huksley** [comment]
Ooh I will try to find a problem and make a patch...

Btw thanks for MSM! 5 years in production and works like a charm!

**Comment by MikeMirzayanov** [comment]
The issue that `org.apache.catalina.Manager#getContainer().getLoader()` is no longer available in catalina version 8. You may use `org.apache.catalina.Manager#getContext().getLoader()`, but it is not available in catalina version 6.
