### ISSUE TITLE
IllegalStateException with tomcat 7 and JavolutionTranscoder

### ISSUE THREAD

**Issue by caboteria** [magro/memcached-session-manager#288]
I'm using msm 1.9.2 with tomcat 7.0.54 on Centos7 and it works great with the default serializer.  Thanks!

I'd like to use the Javolution serializer so that other non-Java platforms could potentially share the session data, but when I configure with de.javakaffee.web.msm.serializer.javolution.JavolutionTranscoderFactory I can log in and get pages but when I submit a form (in my Grails app) I get this stack trace:

```
Mar 07, 2016 9:31:45 AM de.javakaffee.web.msm.MemcachedSessionService loadFromMemcached
WARNING: Could not deserialize session with id D8F891405F9B678A5556B7365CB7DF74-n1 from memcached, session will be purged from storage.
de.javakaffee.web.msm.TranscoderDeserializationException: java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at de.javakaffee.web.msm.serializer.javolution.JavolutionTranscoder.doDeserialize(JavolutionTranscoder.java:179)
	at de.javakaffee.web.msm.serializer.javolution.JavolutionTranscoder.deserializeAttributes(JavolutionTranscoder.java:159)
	at de.javakaffee.web.msm.TranscoderService.deserializeAttributes(TranscoderService.java:170)
	at de.javakaffee.web.msm.TranscoderService.deserialize(TranscoderService.java:127)
	at de.javakaffee.web.msm.MemcachedSessionService.loadFromMemcached(MemcachedSessionService.java:1146)
	at de.javakaffee.web.msm.MemcachedSessionService.findSession(MemcachedSessionService.java:595)
	at de.javakaffee.web.msm.MemcachedBackupSessionManager.findSession(MemcachedBackupSessionManager.java:225)
	at org.apache.catalina.connector.Request.doGetSession(Request.java:2913)
	at org.apache.catalina.connector.Request.getSession(Request.java:2310)
	at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:897)
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:229)
	at org.apache.shiro.web.servlet.ShiroHttpServletRequest.getSession(ShiroHttpServletRequest.java:143)
	at org.apache.shiro.web.session.mgt.ServletContainerSessionManager.getSession(ServletContainerSessionManager.java:77)
	at org.apache.shiro.mgt.SessionsSecurityManager.getSession(SessionsSecurityManager.java:125)
	at org.apache.shiro.mgt.DefaultSecurityManager.resolveContextSession(DefaultSecurityManager.java:456)
	at org.apache.shiro.mgt.DefaultSecurityManager.resolveSession(DefaultSecurityManager.java:442)
	at org.apache.shiro.mgt.DefaultSecurityManager.createSubject(DefaultSecurityManager.java:338)
	at org.apache.shiro.subject.Subject$Builder.buildSubject(Subject.java:846)
	at org.apache.shiro.web.subject.WebSubject$Builder.buildWebSubject(WebSubject.java:148)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.createSubject(AbstractShiroFilter.java:292)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:359)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.shiro.grails.SavedRequestFilter.doFilter(SavedRequestFilter.java:55)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at de.javakaffee.web.msm.RequestTrackingContextValve.invoke(RequestTrackingContextValve.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:124)
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:156)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at org.springframework.web.context.request.RequestContextHolder.currentRequestAttributes(RequestContextHolder.java:131)
	at org.codehaus.groovy.grails.web.servlet.GrailsFlashScope.registerWithSessionIfNecessary(GrailsFlashScope.java:199)
	at org.codehaus.groovy.grails.web.servlet.GrailsFlashScope.put(GrailsFlashScope.java:155)
	at de.javakaffee.web.msm.serializer.javolution.ReflectionBinding$XMLMapFormat.read(ReflectionBinding.java:428)
	at de.javakaffee.web.msm.serializer.javolution.ReflectionBinding$XMLMapFormat.read(ReflectionBinding.java:389)
	at javolution.xml.XMLFormat$InputElement.readInstanceOf(XMLFormat.java:507)
	at javolution.xml.XMLFormat$InputElement.get(XMLFormat.java:403)
	at de.javakaffee.web.msm.serializer.javolution.ReflectionBinding$XMLMapFormat.read(ReflectionBinding.java:428)
	at de.javakaffee.web.msm.serializer.javolution.ReflectionBinding$XMLMapFormat.read(ReflectionBinding.java:389)
	at javolution.xml.XMLFormat$InputElement.readInstanceOf(XMLFormat.java:507)
	at javolution.xml.XMLFormat$InputElement.get(XMLFormat.java:403)
	at javolution.xml.XMLObjectReader.read(XMLObjectReader.java:239)
	at de.javakaffee.web.msm.serializer.javolution.JavolutionTranscoder.doDeserialize(JavolutionTranscoder.java:176)
	... 51 more
```

Have I mis-configured something?  Any ideas I should look at?

Thanks...

**Comment by caboteria** [comment]
I switched to the XStream serializer and that looks like it's working well.

**Comment by magro** [comment]
@caboteria Great that it's working for you with xstream!

GrailsFlashScope is indeed "special", see e.g. [this post on the mailing list](https://groups.google.com/forum/#!topic/memcached-session-manager/ioHnsfscIjA). If you want to use javolution you might try to write a custom serializer for it.

I'm closing this for now, reopen if necessary.
