### ISSUE TITLE
error using kyro serialization with GrailsFlashScopeRegistration

### ISSUE THREAD

**Issue by j4y** [magro/memcached-session-manager#290]
I'm trying to use Grails 2.2.4, Tomcat 7, memecached-session-manager 1.9.2 with kryo serialization

It's unable to find this class: org.codehaus.groovy.grails.web.servlet.GrailsFlashScope

Looks like this recently changed in commit 107c698a4af32f5d50565912e142af1e2c23aaa1

Any ideas what do to here?

```
WARNING: Could not deserialize session with id C3D2B7D7646530ED19BF4643800F6D1B-n1 from memcached, session will be purged from storage.
de.javakaffee.web.msm.TranscoderDeserializationException: com.esotericsoftware.kryo.KryoException: Unable to find class: org.codehaus.groovy.grails.web.servlet.GrailsFlashScope
	at de.javakaffee.web.msm.serializer.kryo.KryoTranscoder.deserializeAttributes(KryoTranscoder.java:212)
	at de.javakaffee.web.msm.TranscoderService.deserializeAttributes(TranscoderService.java:170)
	at de.javakaffee.web.msm.TranscoderService.deserialize(TranscoderService.java:127)
	at de.javakaffee.web.msm.MemcachedSessionService.loadFromMemcached(MemcachedSessionService.java:1146)
	at de.javakaffee.web.msm.MemcachedSessionService.findSession(MemcachedSessionService.java:595)
	at de.javakaffee.web.msm.MemcachedBackupSessionManager.findSession(MemcachedBackupSessionManager.java:225)
	at org.apache.catalina.connector.Request.doGetSession(Request.java:2913)
	at org.apache.catalina.connector.Request.getSessionInternal(Request.java:2531)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:426)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:156)
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:124)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.esotericsoftware.kryo.KryoException: Unable to find class: org.codehaus.groovy.grails.web.servlet.GrailsFlashScope
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:156)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133)
```

Context.xml config:
```
    <Manager
        className="de.javakaffee.web.msm.MemcachedBackupSessionManager"
        memcachedNodes="n1:memecached.example.com:11211"
        sticky="false"
        sessionBackupAsync="false"
        sessionBackupTimeout="1000"
        lockingMode="all"
        transcoderFactoryClass="de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory"
        customConverter="de.javakaffee.web.msm.serializer.kryo.GrailsFlashScopeRegistration"
        requestUriIgnorePattern=".*/static/.*\.(ico|png|gif|jpg|css|js|swf|svg|ttf|wott|eot)$"
    />
```

**Comment by j4y** [comment]
I resolved this by downgrading memcached-session-manager from 1.9.2 to 1.8.3

Grails 2.2.5 apparently uses org.codehaus.groovy.grails.web.servlet.GrailsFlashScope and in memcache-session-manager 1.9.2 it was switched to org.grails.web.servlet.GrailsFlashScope in commit 107c698

I suspect that newer versions of grails use org.grails.web.servlet.GrailsFlashScope instead of org.codehaus.groovy.grails.web.servlet.GrailsFlashScope

**Comment by magro** [comment]
You could create your own GrailsFlashScopeRegistration for the older class...

**Comment by magro** [comment]
@j4y can we close this issue?
