### ISSUE TITLE
Incorrectly appends default port to provided port, thus breaking all session functionality

### ISSUE THREAD

**Issue by edwardotis** [magro/memcached-session-manager#294]
On Tomcat 8.0.30, oracle jdk 8.77
Using https://github.com/jsimone/webapp-runner with server string for MEMCACHE_SERVERS:
 n1:pub-memcache-42.us-east-1-1.1.ec2.garantiadata.com:11733

Results in default port being appended to provided port:
a
Apr 13, 2016 4:52:57 AM de.javakaffee.web.msm.MemcachedSessionService startInternal
INFO:  starts initialization... (configured nodes definition n1:pub-memcache-42.us-east-1-1.1.ec2.garantiadata.com:11733:11211, failover nodes null)
Apr 13, 2016 4:52:57 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: The session manager failed to start
org.apache.catalina.LifecycleException: Failed to start component [de.javakaffee.web.msm.MemcachedBackupSessionManager[]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5272)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Configured memcachedNodes attribute has wrong format, must match ([\w]+):([^:]+):([\d]+)(?:(?:\s+|,)([\w]+):([^:]+):([\d]+))*
	at de.javakaffee.web.msm.MemcachedNodesManager.createFor(MemcachedNodesManager.java:190)
	at de.javakaffee.web.msm.MemcachedSessionService.createMemcachedNodesManager(MemcachedSessionService.java:480)
	at de.javakaffee.web.msm.MemcachedSessionService.startInternal(MemcachedSessionService.java:423)
	at de.javakaffee.web.msm.MemcachedBackupSessionManager.startInternal(MemcachedBackupSessionManager.java:518)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 8 more

Reference:
https://github.com/jsimone/webapp-runner/issues/60

**Comment by edwardotis** [comment]
Sorry, confirmed that this is entirely a bug in:
https://github.com/jsimone/webapp-runner/issues/60
