### ISSUE TITLE
can not serialize with Kryo

### ISSUE THREAD

**Issue by lenxeon** [magro/memcached-session-manager#296]
project git address : https://github.com/dangdangdotcom/config-toolkit

exceptions:

_authService (com.dangdang.config.service.web.mb.NodeAuthManagedBean)
	at de.javakaffee.web.msm.serializer.kryo.KryoTranscoder.serializeAttributes(KryoTranscoder.java:232)
	at de.javakaffee.web.msm.TranscoderService.serializeAttributes(TranscoderService.java:154)
	at de.javakaffee.web.msm.BackupSessionTask.serializeAttributes(BackupSessionTask.java:180)
	at de.javakaffee.web.msm.BackupSessionTask.call(BackupSessionTask.java:110)
	at de.javakaffee.web.msm.BackupSessionTask.call(BackupSessionTask.java:51)
	at de.javakaffee.web.msm.BackupSessionService$SynchronousExecutorService.submit(BackupSessionService.java:346)
	... 15 more
Caused by: com.esotericsoftware.kryo.KryoException: java.util.ConcurrentModificationException
Serialization trace:
classes (java.net.URLClassLoader)
classloader (java.security.ProtectionDomain)
context (java.security.AccessControlContext)
acc (org.apache.catalina.loader.WebappClassLoader)
contextClassLoader (org.apache.zookeeper.ClientCnxn$EventThread)
eventThread (org.apache.zookeeper.ClientCnxn)
cnxn (org.apache.zookeeper.ZooKeeper)
zooKeeperHandle (org.apache.curator.HandleHolder$1)
this$1 (org.apache.curator.HandleHolder$1$1)
helper (org.apache.curator.HandleHolder)
zooKeeper (org.apache.curator.ConnectionState)
state (org.apache.curator.CuratorZookeeperClient)
client (org.apache.curator.framework.imps.CuratorFrameworkImpl)
client (com.dangdang.config.service.zkdao.AuthDao)
authDao (com.dangdang.config.service.AuthService)
authService (com.dangdang.config.service.web.mb.NodeAuthManagedBean)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:101)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:628)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:366)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:307)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)
	at com.esotericsoftware.kryo.Kryo.writeObjectOrNull(Kryo.java:606)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:87)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:628)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:113)
	at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:39)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:534)
	at de.javakaffee.web.msm.serializer.kryo.KryoTranscoder.serializeAttributes(KryoTranscoder.java:229)
	... 20 more
Caused by: java.util.ConcurrentModificationException
	at java.util.Vector$Itr.checkForComodification(Vector.java:1156)
	at java.util.Vector$Itr.next(Vector.java:1133)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:92)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:40)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)
	... 74 more_

**Comment by magro** [comment]
Looking at the serialization trace it seems nearly the whole world/app is serialized:

```
classes (java.net.URLClassLoader)
classloader (java.security.ProtectionDomain)
context (java.security.AccessControlContext)
acc (org.apache.catalina.loader.WebappClassLoader)
contextClassLoader (org.apache.zookeeper.ClientCnxn$EventThread)
eventThread (org.apache.zookeeper.ClientCnxn)
cnxn (org.apache.zookeeper.ZooKeeper)
zooKeeperHandle (org.apache.curator.HandleHolder$1)
this$1 (org.apache.curator.HandleHolder$1$1)
helper (org.apache.curator.HandleHolder)
zooKeeper (org.apache.curator.ConnectionState)
state (org.apache.curator.CuratorZookeeperClient)
client (org.apache.curator.framework.imps.CuratorFrameworkImpl)
client (com.dangdang.config.service.zkdao.AuthDao)
authDao (com.dangdang.config.service.AuthService)
authService (com.dangdang.config.service.web.mb.NodeAuthManagedBean)
```

This is probably not what you want. For some class (e.g. `NodeAuthManagedBean` or s.th. "above" holding such a bean) you should customize serialization. You could also set e.g. `NodeAuthManagedBean.authService` to transient.
In either case you need to reinject `@ManagedProperty`s on deserialization. Not sure if jsf provides some specified way to do this, perhaps you have to check out implementation specific stuff (if the glassfish jsf implementation provides s.th.). Out of interest I searched the web for reinjecting transient beans, perhaps these 2 results provide some inspiration:
http://stackoverflow.com/questions/10618123/how-to-re-inject-a-transient-managedproperty-at-deserializing
http://www.beyondjava.net/blog/integrate-jsf-2-spring-3-nicely/
