### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: org/objenesis/strategy/InstantiatorStrategy

### ISSUE THREAD

**Issue by xingkaihu** [magro/memcached-session-manager#297]
download the below jars and put them in $CATALINA_HOME/lib/.
jars list：
asm-5.1.jar
kryo-3.0.3.jar
kryo-serializers-0.37.jar
memcached-session-manager-1.9.2.jar
memcached-session-manager-tc8-1.9.2.jar
minlog-1.3.0.jar
msm-kryo-serializer-1.9.1.jar
reflectasm-1.11.3.jar
spymemcached-2.11.1.jar

 exception logs with running tomcat8  ==============>>>

26-May-2016 01:04:11.349 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal The session manager failed to start
 org.apache.catalina.LifecycleException: Failed to start component [de.javakaffee.web.msm.MemcachedBackupSessionManager[/host-manager]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5289)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/objenesis/strategy/InstantiatorStrategy
	at de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory.getTranscoder(KryoTranscoderFactory.java:64)
	at de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory.createTranscoder(KryoTranscoderFactory.java:47)
	at de.javakaffee.web.msm.MemcachedSessionService.createTranscoderService(MemcachedSessionService.java:493)
	at de.javakaffee.web.msm.MemcachedSessionService.startInternal(MemcachedSessionService.java:448)
	at de.javakaffee.web.msm.MemcachedBackupSessionManager.startInternal(MemcachedBackupSessionManager.java:518)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	... 12 more
Caused by: java.lang.ClassNotFoundException: org.objenesis.strategy.InstantiatorStrategy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more

**Comment by xingkaihu** [comment]
I added mockito-all-1.10.19.jar into  $CATALINA_HOME/lib/ directory,and then run tomcat8 without exception. 
All configs  referred url from  https://github.com/magro/memcached-session-manager/wiki/SetupAndConfiguration . I don't know the configure is  if right, anyone has some idea?

**Comment by magro** [comment]
Because you're getting "ClassNotFoundException:
org.objenesis.strategy.InstantiatorStrategy" I'd say you should add the
objenesis jar. Documentation seems to be outdated here.

Cheers,
Martin

keifer <notifications@github.com> schrieb am Do., 26. Mai 2016, 10:35:

**Comment by xingkaihu** [comment]
For testing ,set value into session in the jsp 
===============jsp start=======================
<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%>
<%
	String sessionId = session.getId();
	session.setAttribute("test", "test by keifer");
%>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
 <title>test msm</title>
</head>
<body>
<div class="container">
	sessionId=<%=sessionId %>
</div>
</body>
</html>
===================end===================

When to access, tomcat logs had exception below===========>>
26-May-2016 23:45:03.464 SEVERE [http-nio-18080-exec-7] org.apache.coyote.http11.AbstractHttp11Processor.process Error processing request
 java.lang.NoSuchFieldError: attributes
	at de.javakaffee.web.msm.MemcachedBackupSession.getAttributesFiltered(MemcachedBackupSession.java:522)
	at de.javakaffee.web.msm.BackupSessionTask.call(BackupSessionTask.java:109)
	at de.javakaffee.web.msm.BackupSessionTask.call(BackupSessionTask.java:51)
	at de.javakaffee.web.msm.BackupSessionService$SynchronousExecutorService.submit(BackupSessionService.java:346)
	at de.javakaffee.web.msm.BackupSessionService.backupSession(BackupSessionService.java:205)
	at de.javakaffee.web.msm.MemcachedSessionService.backupSession(MemcachedSessionService.java:1084)
	at de.javakaffee.web.msm.RequestTrackingHostValve.backupSession(RequestTrackingHostValve.java:230)
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:159)
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:124)
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:124)
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:124)
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:124)
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:124)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by magro** [comment]
Weird, which version of tomcat are you using?

Btw, as said in [SetupAndConfiguration](https://github.com/magro/memcached-session-manager/wiki/SetupAndConfiguration#add-custom-serializers-to-your-webapp-optional) serialization jars (msm-kryo-serializer and all transitive dependencies) should go into `WEB-INF/lib/` instead of `$CATALINA_HOME/lib/`.

**Comment by nhsoft** [comment]
> which version of tomcat are you using?
Tomcat 8.0.35 with JDK1.8.0.91.

serialization jars (msm-kryo-serializer and all transitive dependencies)  copy into _WEB-INF/lib/_, the same error will appear.

sticky="true"，config detail 

>  <Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"
> 		memcachedNodes="c9cf2d23bdc2455b.m.cnhzaliqshpub001.ocs.aliyuncs.com:11211"
> 		username="c9cf2d23bdc2455b" 
> 		password="IJ5aWD1YRAS8q9fV"
> 		memcachedProtocol="binary"
> 		**sticky="true"**
> 		sessionBackupAsync="false"
> 		requestUriIgnorePattern=".*\.(ico|png|gif|jpg|css)$"
> 		transcoderFactoryClass="de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory"/>

it works

**Comment by magro** [comment]
Can you test non-sticky with tomcat 8.0.32? 

Because you said you *copied* jars (instead of move): serialization jars (msm-kryo-serializer and all transitive dependencies) must not be in $CATALINA_HOME/lib/, so maybe you have to delete them there.

**Comment by magro** [comment]
@xingkaihu I just released msm 1.9.3 with the fix for `java.lang.NoSuchFieldError: attributes`. If there are still issues please reopen.

**Comment by nhsoft** [comment]
after upgrade to 1.9.3, it works.
