### ISSUE TITLE
Tomcat 8.5 support

### ISSUE THREAD

**Issue by Ironlink** [magro/memcached-session-manager#303]
In Tomcat 8.5, the method StandardSession.exclude now takes two parameters instead of one.

The Tomcat devs would prefer if this change was handled on the msm side, see bugzilla:
https://bz.apache.org/bugzilla/show_bug.cgi?id=59735

**Comment by magro** [comment]
I just released 1.9.4 with the fix, please let me know how it works for you.

**Comment by Ironlink** [comment]
I have found one other issue, with this stack trace:
```
21-Jun-2016 10:40:27.440 INFO [ContainerBackgroundProcessor[StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]] de.javakaffee.web.msm.MemcachedSessionService.updateExpirationInMemcached Could not update expiration in memcached for session 7C848BA7F54EBAEBF018E9B719A83F0D-n2
 java.lang.NoSuchMethodError: org.apache.catalina.Manager.getContainer()Lorg/apache/catalina/Container;
	at de.javakaffee.web.msm.MemcachedBackupSession.getMemcachedExpirationTimeToSet(MemcachedBackupSession.java:275)
	at de.javakaffee.web.msm.BackupSessionTask.storeSessionInMemcached(BackupSessionTask.java:229)
	at de.javakaffee.web.msm.BackupSessionTask.doBackupSession(BackupSessionTask.java:199)
	at de.javakaffee.web.msm.BackupSessionService.updateExpiration(BackupSessionService.java:134)
	at de.javakaffee.web.msm.MemcachedSessionService.updateExpirationInMemcached(MemcachedSessionService.java:1606)
	at de.javakaffee.web.msm.MemcachedBackupSessionManager.backgroundProcess(MemcachedBackupSessionManager.java:575)
	at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5543)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1374)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1346)
	at java.lang.Thread.run(Thread.java:745)
```
The method Manager.getContainer() has been replaced by Manager.getContext(). Should I open a new issue for this?

**Comment by magro** [comment]
It's enough to change the title of the issue to s.th. more general :-) Let's see how many rounds it takes until all issues are sorted out :-)

**Comment by magro** [comment]
While upgrading the tomcat 8 dependency to 8.5.3 I realized that this jaspic stuff was added, which fails lots of tests. I need to go through them an understand jaspic for the right solution, this may take some time. If you're in a hurry feel free to submit a pull request :-)

**Comment by magro** [comment]
I just released msm 1.9.5, please let me know how it works for you.

**Comment by magro** [comment]
@Ironlink Could you already test 1.9.5, how does it work for you?

**Comment by martincizek** [comment]
Unfortunately this breaks MSM functionality with older Tomcats, which are used in stable Linux distributions (e.g. Debian Jessie: 8.0.14, wheezy-backports: 8.0.14,  jessie-bacports: 8.0.32).
Any chance to support both old and new Tomcats by accessing the changed Tomcat API using reflection calls?

**Comment by magro** [comment]
@martincizek Can you provide more details, tomcat version + the actual error with stack trace? The goal is in fact to support older tomcat versions.

**Comment by magro** [comment]
@martincizek Sorry, reading again I realized you actually stated the tomcat versions. If you could provide a stack trace this would still be helpful.

**Comment by martincizek** [comment]
The log from Tomcat 8.0.14 and MSM 1.9.5 follows below. The log from Tomcat 7.0.56 looks the very same.
As it could be expected, it complains about non-existence of the two-parameter method `StandardSession.exclude(String, Object)`.

I can imagine three solutions:

1. More tomcat-version-specific JARs (i.e. JAR for tc8 would be relased as memcached-session-manager-tc8.0.0-${version}.jar, memcached-session-manager-tc8.0.31-${version}.jar and similarly for tc7 and tc6 eventually).
2. Determine and call the right method using reflection, i.e. trying to call `getClass().getMethod("exclude", String.class, Object.class).invoke(name, value)` and if that fails, then use one-parameter variant. Can be optimized by determining the right way in advance indeed.
3. Or at least documenting the supported Tomcat versions for each Tomcat (for tc8 it should be 8.0.31+).
```
VIII 01, 2016 11:02:41 DOP. de.javakaffee.web.msm.MemcachedSessionService createSession
FINE: createSession invoked: null
VIII 01, 2016 11:02:41 DOP. de.javakaffee.web.msm.SessionIdFormat createSessionId
FINE: Creating new session id with orig id 'ping' and memcached id 'n1'.
VIII 01, 2016 11:02:41 DOP. de.javakaffee.web.msm.NodeAvailabilityCache updateIsNodeAvailable
FINE: CacheLoader returned node availability 'true' for node 'n1'.
VIII 01, 2016 11:02:41 DOP. de.javakaffee.web.msm.SessionIdFormat createSessionId
FINE: Creating new session id with orig id '81E4FC5ECF9E8D89EFA059013600B203' and memcached id 'n1'.
VIII 01, 2016 11:02:41 DOP. de.javakaffee.web.msm.MemcachedSessionService createSession
FINE: Created new session with id 81E4FC5ECF9E8D89EFA059013600B203-n1
VIII 01, 2016 11:02:41 DOP. de.javakaffee.web.msm.BackupSessionService backupSession
FINE: Starting for session id 81E4FC5ECF9E8D89EFA059013600B203-n1
VIII 01, 2016 11:02:41 DOP. de.javakaffee.web.msm.BackupSessionTask call
FINE: Starting for session id 81E4FC5ECF9E8D89EFA059013600B203-n1
VIII 01, 2016 11:02:41 DOP. org.apache.coyote.ajp.AbstractAjpProcessor process
SEVERE: Error processing request
java.lang.NoSuchMethodError: org.apache.catalina.session.StandardSession.exclude(Ljava/lang/String;Ljava/lang/Object;)Z
        at de.javakaffee.web.msm.MemcachedBackupSession.exclude(MemcachedBackupSession.java:597)
        at de.javakaffee.web.msm.JavaSerializationTranscoder.writeAttributes(JavaSerializationTranscoder.java:121)
        at de.javakaffee.web.msm.JavaSerializationTranscoder.serializeAttributes(JavaSerializationTranscoder.java:100)
        at de.javakaffee.web.msm.TranscoderService.serializeAttributes(TranscoderService.java:151)
        at de.javakaffee.web.msm.BackupSessionTask.serializeAttributes(BackupSessionTask.java:180)
        at de.javakaffee.web.msm.BackupSessionTask.call(BackupSessionTask.java:110)
        at de.javakaffee.web.msm.BackupSessionTask.call(BackupSessionTask.java:51)
        at de.javakaffee.web.msm.BackupSessionService$SynchronousExecutorService.submit(BackupSessionService.java:347)
        at de.javakaffee.web.msm.BackupSessionService.backupSession(BackupSessionService.java:206)
        at de.javakaffee.web.msm.MemcachedSessionService.backupSession(MemcachedSessionService.java:1086)
        at de.javakaffee.web.msm.RequestTrackingHostValve.backupSession(RequestTrackingHostValve.java:230)
        at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:159)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
        at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:827)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by magro** [comment]
Right, this was broken with https://github.com/magro/memcached-session-manager/commit/ef5ca89109bafa73e9cac2697fc1d7c4708bdcd0. My preference would be to use reflection, s.th. similar was introduced to MemcachedBackupSession in  https://github.com/magro/memcached-session-manager/commit/aa084dc1fe481101eac395654631abb1fd7e49d7. 

Do you want to submit a pull request?

**Comment by martincizek** [comment]
> Do you want to submit a pull request?

My colleague will try to.

**Comment by magro** [comment]
@martincizek Thanks as well, the PR is released with 1.9.7.

**Comment by martincizek** [comment]
@magro You're welcome. It was quite tricky as it is not possible to call super's method using reflection. So on old Tomcat, there is actually a reference to a non-existing super's method. We rely on that this reference does not cause problem when it is in an unexecuted code branch.

**Comment by dishadutta26** [comment]
@magro  For one of our client, we were using Memcache-1.9.2 along with tomcat 8.0.30. We upgraded tomcat to 8.5.31. I wanted to know if Memcache 2.2.0 would be right fir for it?

**Comment by joinsafehouse** [comment]
It will get resolve if you user memcached-session-manager-tc8-2.3.0.jar and memcached-session-manager-2.3.0.jar
