### ISSUE TITLE
ClassNotFoundException: com.couchbase.client.CouchbaseClient

### ISSUE THREAD

**Issue by daralisp** [magro/memcached-session-manager#305]
Im trying to use CouchBaseClient but getting NoClassDefFoundError: 
Please help. I have no idea why? 
Thanks so much.

Below are info in my .classpath, exception and my test code:

.classpath includes:
jettison-1.1.jar"/>
netty-3.2.0.Final.jar"/>
commons-codec-1.5.jar"/>
couchbase-client-1.0.1.jar"/>
spymemcached-2.8.0.jar"/>

Exception in thread "main" java.lang.NoClassDefFoundError: com/couchbase/client/CouchbaseClient
at com.adxpose.test.CouchbaseClientTest.main(CouchbaseClientTest.java:22)
Caused by: java.lang.ClassNotFoundException: com.couchbase.client.CouchbaseClient
at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

My testcode: 
import java.net.URI;
import java.util.ArrayList;

import com.couchbase.client.CouchbaseClient;

public class CouchbaseClientTest {

public static void main(String args[]) {
    // Set the URIs and get a client
    try {
        ArrayList<URI> uris = new ArrayList<URI>();
        uris.add(URI.create("http://127.0.0.1:11211/pools"));

```
    CouchbaseClient c = new CouchbaseClient(uris, "default", "");
    c.set("keyTest", 0, "Hello World");
    System.out.println(c.get("key"));
    System.out.println(c.get("keyTest").toString());
} catch (Exception e) {
    System.err.println("Error connecting to Couchbase: "
            + e.getMessage());
    System.exit(0);
}
```

}
}

**Comment by magro** [comment]
Not sure what's the relation on this project. Anyways, does the stack trace contain more "Caused by"s? Are your libs versions compatible?
