### ISSUE TITLE
Failed to start component

### ISSUE THREAD

**Issue by paddy235** [magro/memcached-session-manager#308]
# use jars:
memcached-session-manager-1.9.5.jar
memcached-session-manager-tc8-1.9.5.jar	
spymemcached-2.12.0.jar
msm-kryo-serializer-1.9.5.jar
kryo-serializers-0.37.jar
kryo-3.0.3.jar

# use tomat version: 8.0.33
# tomcat context.xml 

<Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"
    memcachedNodes="n1:10.150.103.2:11211"
    failoverNodes="n1"
    requestUriIgnorePattern=".*\.(ico|png|gif|jpg|css|js)$"
    transcoderFactoryClass="de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory"
    />

# issue 

INFO localhost-startStop-1 de.javakaffee.web.msm.MemcachedBackupSessionManager$1 -  starts initialization... (configured nodes definition n1:10.150.103.2:11211, failover nodes n1)
ERROR localhost-startStop-1 org.apache.catalina.core.StandardContext - The session manager failed to start
org.apache.catalina.LifecycleException: Failed to start component [de.javakaffee.web.msm.MemcachedBackupSessionManager[/dev.sf.eccl]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5289)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: For a single memcached node there should/must no failoverNodes be specified.
	at de.javakaffee.web.msm.MemcachedNodesManager.createFor(MemcachedNodesManager.java:232)
	at de.javakaffee.web.msm.MemcachedSessionService.createMemcachedNodesManager(MemcachedSessionService.java:491)
	at de.javakaffee.web.msm.MemcachedSessionService.startInternal(MemcachedSessionService.java:434)
	at de.javakaffee.web.msm.MemcachedBackupSessionManager.startInternal(MemcachedBackupSessionManager.java:537)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	... 12 more
ERROR localhost-startStop-1 org.apache.catalina.core.StandardContext - The session manager failed to start
org.apache.catalina.LifecycleException: Failed to start component [de.javakaffee.web.msm.MemcachedBackupSessionManager[/dev.sf.eccl]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5289)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: For a single memcached node there should/must no failoverNodes be specified.
	at de.javakaffee.web.msm.MemcachedNodesManager.createFor(MemcachedNodesManager.java:232)
	at de.javakaffee.web.msm.MemcachedSessionService.createMemcachedNodesManager(MemcachedSessionService.java:491)
	at de.javakaffee.web.msm.MemcachedSessionService.startInternal(MemcachedSessionService.java:434)
	at de.javakaffee.web.msm.MemcachedBackupSessionManager.startInternal(MemcachedBackupSessionManager.java:537)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)

**Comment by magro** [comment]
As the exception says: "For a single memcached node there should/must no failoverNodes be specified."

What's not clear with this error message?
