### ISSUE TITLE
No node found for key bak:01FB19C9509FE49ABC40010E3ECFBFAD-n3 (nodeId: null, known nodeIds: [n4, n3])

### ISSUE THREAD

**Issue by kaaloo** [magro/memcached-session-manager#322]
Hi,

I'm getting a strange exception (perhaps the error message is misleading ?) in production every once in a while.  Seems parsing the key for the node in this case would be particularly simple. I doesn't seem to have a effect on our users or system.

> java.lang.IllegalArgumentException: No node found for key bak:01FB19C9509FE49ABC40010E3ECFBFAD-n3 (nodeId: null, known nodeIds: [n4, n3])
        at de.javakaffee.web.msm.SuffixBasedNodeLocator.getPrimary(SuffixBasedNodeLocator.java:101)
        at net.spy.memcached.MemcachedConnection.addOperation(MemcachedConnection.java:1205)
        at net.spy.memcached.MemcachedConnection.enqueueOperation(MemcachedConnection.java:1185)
        at net.spy.memcached.MemcachedClient.delete(MemcachedClient.java:2339)
        at net.spy.memcached.MemcachedClient.delete(MemcachedClient.java:2295)
        at de.javakaffee.web.msm.storage.MemcachedStorageClient.delete(MemcachedStorageClient.java:67)
        at de.javakaffee.web.msm.LockingStrategy.onAfterDeleteFromMemcached(LockingStrategy.java:384)
        at de.javakaffee.web.msm.MemcachedSessionService.deleteFromMemcached(MemcachedSessionService.java:856)
        at de.javakaffee.web.msm.MemcachedBackupSessionManager.removeInternal(MemcachedBackupSessionManager.java:195)
        at de.javakaffee.web.msm.MemcachedBackupSessionManager.remove(MemcachedBackupSessionManager.java:181)
        at org.apache.catalina.session.StandardSession.expire(StandardSession.java:832)
        at org.apache.catalina.session.StandardSession.expire(StandardSession.java:731)
        at org.apache.catalina.session.StandardSession.invalidate(StandardSession.java:1263)
        at org.apache.catalina.session.StandardSessionFacade.invalidate(StandardSessionFacade.java:183)
        at javax.servlet.http.HttpSession$invalidate$9.call(Unknown Source)

**Comment by kaaloo** [comment]
I forgot to mention this is on 2.0.0. Thanks!

**Comment by magro** [comment]
According to the stack trace this happens during session invalidation triggered by tomcat - this explains why there's no impact on users.

The `IllegalArgumentException: No node found for key bak:01FB19C9509FE49ABC40010E3ECFBFAD-n3 (nodeId: null, known nodeIds: [n4, n3])` is thrown in this context when the memcached node "n4" is not available, this is the only possible reason for `nodeId: null` in `SuffixBasedNodeLocator.getPrimary` when the key is a backup key (starts with "bak:").

In this context this is not an issue and I'd say it's a matter of improving logging / exception handling: `LockingStrategy.onAfterDeleteFromMemcached` in this case should not rethrow the exception but gracefully handle it and log info or log debug this case.

Can you share the full stack trace that also shows the logging class?

**Comment by magro** [comment]
Closed via 30315d8d8f
