### ISSUE TITLE
Tomcat authentication on servlet throws serialization exception

### ISSUE THREAD

**Issue by nyx93** [magro/memcached-session-manager#335]
**having **any authentication** **done by tomcat on servlets** throws a **serialization exception****
example: authentication on tomcat manager 
**stack trace:**
24-Jan-2017 15:12:45.596 WARNING [msm-storage-thread-2] de.javakaffee.web.msm.BackupSessionTask.call FAILED for session id 997C1C88C2A62C89AD10D6318CBC4DDD
 java.lang.IllegalArgumentException: Non-serializable object
	at de.javakaffee.web.msm.TranscoderService.serializePrincipal(TranscoderService.java:352)
	at de.javakaffee.web.msm.TranscoderService.serializeSessionFields(TranscoderService.java:197)
	at de.javakaffee.web.msm.TranscoderService.serializeSessionFields(TranscoderService.java:190)
	at de.javakaffee.web.msm.TranscoderService.serialize(TranscoderService.java:180)
	at de.javakaffee.web.msm.BackupSessionTask.call(BackupSessionTask.java:117)
	at de.javakaffee.web.msm.BackupSessionTask.call(BackupSessionTask.java:50)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.NotSerializableException: org.apache.catalina.realm.GenericPrincipal
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.writeObject(Unknown Source)
	at de.javakaffee.web.msm.MemcachedBackupSessionManager.writePrincipal(MemcachedBackupSessionManager.java:885)
	at de.javakaffee.web.msm.TranscoderService.serializePrincipal(TranscoderService.java:348)
	... 9 more

_tomcat version : 8.0.15
Java version: multiple versions/ Java 7.X, Java 8.x
technology used: elastic cache memcached
Jars tested with: 
latest Jar from elastic cache: AmazonElastiCacheClusterClient-1.1.1.jar
memcached-session-manager-2.0.0.jar , 2.1.0, 2.1.1, 1.8.3
memcached-session-manager-tc8-2.0.0.jar , 2.1.0, 2.1.1, 1.8.3
configuration for memcached:
	<Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"
     memcachedNodes="elastic cache end point/ memcached"
     requestUriIgnorePattern=".*\.(ico|png|gif|jpg|css|js)$"
     sticky="false"/>_

**the same stack trace happens on all combinations mentioned above**

**Comment by magro** [comment]
The `GenericPrincipal` in the latest tomcat 8.0 version implements `Serializable`, according to https://tomcat.apache.org/tomcat-8.0-doc/api/org/apache/catalina/realm/GenericPrincipal.html.

In previous versions it did _not_ implement `Serializable`, this was changed with [this commit](https://github.com/apache/tomcat/commit/7d23b388785ac66f4228f717b0adaca0c16b9552) (2014-12-16). According to the tomcat [changelog](https://tomcat.apache.org/tomcat-8.0-doc/changelog.html) 8.0.15 was released 2014-11-07.

I'd suggest you use the latest tomcat 8.5.x release, alternatively a current 8.0.x release could work.

**Comment by nyx93** [comment]
unfortunately i cannot upgrade my tomcat (for compatibility issues with other tools), but i cannot use the session manager as is, would like to double check with you on changing a small part of the implementation of the session manager? i will be changing the read/write principle methods to force-serialize the principle by casting it to a serializableprinciple.

**Comment by magro** [comment]
I don't think that this would work. 

In commit https://github.com/magro/memcached-session-manager/commit/343133a58796fda3e20a5311600db2f5d4edb2ab you see the change in msm in reaction to the change in tomcat. AFAICS it was released with msm 1.9.0, so the previous version could work for you.

**Comment by nyx93** [comment]
thank you everything is solved now!

**Comment by magro** [comment]
Great to hear that!
