### ISSUE TITLE
NoSuchMethodError: javolution.lang.Reflection.getInstance()

### ISSUE THREAD

**Issue by like-fly** [magro/memcached-session-manager#353]
Hi ,I use this jars
- asm-5.2.jar
- javolution-5.3.1.jar
- javolution-serializer-2.1.1.jar
- kryo-2.24.0.jar
- kryo-serializer-2.1.1.jar
- kryo-serializers-0.41.jar
- memcached-session-manager-2.1.1.jar
- memcached-session-manager-tc8-2.1.1.jar
- minlog-1.3.0.jar
- reflectasm-1.11.3.jar
- spymemcached-2.12.3.jar

And i got this exception : 
```
The session manager failed to start
org.apache.catalina.LifecycleException: Failed to start component [de.javakaffee.web.msm.MemcachedBackupSessionManager[/twowin]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5331)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: javolution.lang.Reflection.getInstance()Ljavolution/lang/Reflection;
	at de.javakaffee.web.msm.serializer.javolution.ReflectionBinding.<init>(ReflectionBinding.java:98)
	at de.javakaffee.web.msm.serializer.javolution.JavolutionTranscoder.<init>(JavolutionTranscoder.java:90)
	at de.javakaffee.web.msm.serializer.javolution.JavolutionTranscoderFactory.getTranscoder(JavolutionTranscoderFactory.java:56)
	at de.javakaffee.web.msm.serializer.javolution.JavolutionTranscoderFactory.createTranscoder(JavolutionTranscoderFactory.java:43)
	at de.javakaffee.web.msm.MemcachedSessionService.createTranscoderService(MemcachedSessionService.java:496)
	at de.javakaffee.web.msm.MemcachedSessionService.startInternal(MemcachedSessionService.java:451)
	at de.javakaffee.web.msm.MemcachedBackupSessionManager.startInternal(MemcachedBackupSessionManager.java:538)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	... 8 more
```
I use Tomcat 8 and i look javolution 5.3.1 and 5.2.6 and 5.2.3 , They all have no this method.

**Comment by magro** [comment]
According to https://github.com/magro/memcached-session-manager/wiki/SetupAndConfiguration, it must be javolution-5.4.3.1
