### ISSUE TITLE
 Error parsing port number in Redis URL

### ISSUE THREAD

**Issue by aihepide** [magro/memcached-session-manager#363]
I am using Redis as storage.this is my configuration in tomcat about memcachedNodes:
"redis://:admin@localhost:6379".Some execeptions occured when i start up my tomcat like these:
The session manager failed to start
org.apache.catalina.LifecycleException: Failed to start component [de.javakaffee.web.msm.MemcachedBackupSessionManager[/wfs_web]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5526)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1095)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1930)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Could not create memcached client
        at de.javakaffee.web.msm.StorageClientFactory.createStorageClient(StorageClientFactory.java:62)
        at de.javakaffee.web.msm.MemcachedSessionService.createStorageClient(MemcachedSessionService.java:518)
        at de.javakaffee.web.msm.MemcachedSessionService.startInternal(MemcachedSessionService.java:439)
        at de.javakaffee.web.msm.MemcachedBackupSessionManager.startInternal(MemcachedBackupSessionManager.java:552)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        ... 12 more
Caused by: java.lang.IllegalArgumentException: Error parsing port number in Redis URL
        at de.javakaffee.web.msm.storage.RedisStorageClient.<init>(RedisStorageClient.java:72)
        at de.javakaffee.web.msm.StorageClientFactory.createStorageClient(StorageClientFactory.java:51)
        ... 16 more
Does redis not support authentication password?

**Comment by magro** [comment]
This was added with PR #354 but was not released until now - shame on me! ;-)

I promise to push a new release soon.
