### ISSUE TITLE
CheckedOperationTimeoutException

### ISSUE THREAD

**Issue by koulq** [magro/memcached-session-manager#370]
What is the reason memcached can't store session? My memcached started normal, ports were opened, and the firewall closed.The configuration is as follows:

 <Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"
		    sticky="false"
		    memcachedNodes="n1:xx.xx.xx.xx:11211"
		    requestUriIgnorePattern=".*\.(png|gif|jpg|css|js|ico)$"
		    sessionBackupAsync="false"
		    sessionBackupTimeout="1800000"
		    transcoderFactoryClass="de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory"
	   />

2017-11-09 13:13:29,427 [http-bio-8080-exec-17] WARN  de.javakaffee.web.msm.BackupSessionTask- Could not store session F911EB7B1AC42E781A3FD75CCA124720-n1 in memcached.
Note that this session was relocated to this node because the original node was not available.
java.util.concurrent.ExecutionException: net.spy.memcached.internal.CheckedOperationTimeoutException: Operation timed out. - failing node: /xx.xx.xx.xx:11211
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:180)
	at de.javakaffee.web.msm.BackupSessionTask.storeSessionInMemcached(BackupSessionTask.java:235)
	at de.javakaffee.web.msm.BackupSessionTask.doBackupSession(BackupSessionTask.java:198)
	at de.javakaffee.web.msm.BackupSessionTask.call(BackupSessionTask.java:119)
	at de.javakaffee.web.msm.BackupSessionTask.call(BackupSessionTask.java:50)
	at de.javakaffee.web.msm.BackupSessionService$SynchronousExecutorService.submit(BackupSessionService.java:345)
	at de.javakaffee.web.msm.BackupSessionService.backupSession(BackupSessionService.java:204)
	at de.javakaffee.web.msm.MemcachedSessionService.backupSession(MemcachedSessionService.java:1090)
	at de.javakaffee.web.msm.RequestTrackingHostValve.backupSession(RequestTrackingHostValve.java:231)
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:160)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Operation timed out. - failing node: /xx.xx.xx.xx:11211
	... 21 more
2017-11-10 01:05:40,302 [http-bio-8080-exec-9] WARN  de.javakaffee.web.msm.BackupSessionTask- Could not store session 70832B37DDC51BC52F8B66B1A1D091C0-n1 in memcached.
Note that this session was relocated to this node because the original node was not available.
java.util.concurrent.ExecutionException: net.spy.memcached.internal.CheckedOperationTimeoutException: Operation timed out. - failing node: /xx.xx.xx.xx:11211
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:180)
	at de.javakaffee.web.msm.BackupSessionTask.storeSessionInMemcached(BackupSessionTask.java:235)
	at de.javakaffee.web.msm.BackupSessionTask.doBackupSession(BackupSessionTask.java:198)
	at de.javakaffee.web.msm.BackupSessionTask.call(BackupSessionTask.java:119)
	at de.javakaffee.web.msm.BackupSessionTask.call(BackupSessionTask.java:50)
	at de.javakaffee.web.msm.BackupSessionService$SynchronousExecutorService.submit(BackupSessionService.java:345)
	at de.javakaffee.web.msm.BackupSessionService.backupSession(BackupSessionService.java:204)
	at de.javakaffee.web.msm.MemcachedSessionService.backupSession(MemcachedSessionService.java:1090)
	at de.javakaffee.web.msm.RequestTrackingHostValve.backupSession(RequestTrackingHostValve.java:231)
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:160)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Operation timed out. - failing node: /xx.xx.xx.xx:11211
	... 21 more

**Comment by magro** [comment]
Sorry for the late response! The operation timeout points to an infrastructure/networking issue.

Is this still relevant, or can we close this issue?
