### ISSUE TITLE
Please consider support for tomcat 10.1

### ISSUE THREAD

**Issue by gpotagal-WellSky** [magro/memcached-session-manager#459]
Please consider:

- SpringBoot 2.7 is end of life on 18 Nov 2023
- SpringBoot 3.x requires JDK17 and Tomcat 10 - pls see discussion on:
    https://stackoverflow.com/questions/75087509/spring-boot-3-and-spring-6-with-tomcat-9 

Testing with JDK 17 / Tomcat 10 memcached-session-manager 9.3.2 no longer works:

SEVERE [Catalina-utility-2] org.apache.catalina.core.StandardPipeline.addValve Error starting Valve
	org.apache.catalina.LifecycleException: Failed to initialize component [RequestTrackingContextValve[StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]]
		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:419)
		at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:130)
		[......]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:833)
	Caused by: java.lang.NoClassDefFoundError: javax/servlet/ServletException

**Comment by LLY-SC** [comment]
已收到你的邮件，我会尽快与你联系回复！谢谢！！

**Comment by Ampersanta** [comment]
I wonder if thee was any update on it?

**Comment by LLY-SC** [comment]
已收到你的邮件，我会尽快与你联系回复！谢谢！！
