### ISSUE TITLE
msm-javolution-serializer: add xmlformat implementations for more jdk types

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#70]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on December 29, 2009 22:48:32_

Right now the msm-javolution-serializer provides some special xmlformat 
implementations for specific java types. Others are handled by the 
ReflectionFormat.

It should be checked if for some types (e.g. Locale, Currency, Pattern) 
specific xmlformat implementations would be useful.

A good idea of type candidates gives the xstream converters overview: 
<a href="http://xstream.codehaus.org/converters.html" rel="nofollow">http://xstream.codehaus.org/converters.html</a>

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=26_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on December 30, 2009 04:18:58_

<i>(No comment was entered for this change.)</i>

**Labels:** -Release1.1 Release1.2

**Comment by google-code-exporter** [comment]
_From [yoga.und...@gmail.com](https://code.google.com/u/111652832360445102669/) on April 02, 2014 14:41:42_

Hi Martin,

After unsuccessful using msm + kryo/jav + springmvc(leagcy application), tried with JavolutionSerializer, it works fine in my simple mvc application but again failing in our legacy spring MVC application with following error stack.

Is this enhancement available in the latest release ??

Thanks
Yoga

Apr 2, 2014 2:28:10 PM de.javakaffee.web.msm.serializer.javolution.ReflectionFormat writeElements
SEVERE: Could not write element for field.
java.lang.IllegalArgumentException: No suitable constructor found for class java.math.BigInteger.
Available constructors: [public java.math.BigInteger(byte[]), public java.math.BigInteger(int,byte[]), public java.math.BigInteger(java.lang.String,int), public java.math.BigInteger(java.lang.String), public java.math.BigInteger(int,java.util.Random), public java.math.BigInteger(int,int,java.util.Random)]
	at de.javakaffee.web.msm.serializer.javolution.ReflectionFormat.createNumberFormat(ReflectionFormat.java:584)
	at de.javakaffee.web.msm.serializer.javolution.ReflectionFormat.getNumberFormat(ReflectionFormat.java:561)
	at de.javakaffee.web.msm.serializer.javolution.ReflectionBinding.getFormat(ReflectionBinding.java:198)
	at javolution.xml.XMLFormat$OutputElement.add(XMLFormat.java:815)
	at de.javakaffee.web.msm.serializer.javolution.ReflectionFormat.writeElements(ReflectionFormat.java:263)
	at de.javakaffee.web.msm.serializer.javolution.ReflectionFormat.write(ReflectionFormat.java:245)
	at javolution.xml.XMLFormat$OutputElement.add(XMLFormat.java:819)
	at de.javakaffee.web.msm.serializer.javolution.ReflectionFormat.writeElements(ReflectionFormat.java:263)
	at de.javakaffee.web.msm.serializer.javolution.ReflectionFormat.write(ReflectionFormat.java:245)
	at javolution.xml.XMLFormat$OutputElement.add(XMLFormat.java:819)
	at de.javakaffee.web.msm.serializer.javolution.ReflectionFormat.writeElements(ReflectionFormat.java:263)
	at de.javakaffee.web.msm.serializer.javolution.ReflectionFormat.write(ReflectionFormat.java:245)
	at javolution.xml.XMLFormat$OutputElement.add(XMLFormat.java:819)
	at de.javakaffee.web.msm.serializer.javolution.ReflectionFormat.w

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on April 02, 2014 15:30:33_

No, afaics this is not yet implemented. This should be easy to accomplish, I'm open for pull requests (my time is very limited right now).

Cheers,
Martin

**Comment by google-code-exporter** [comment]
_From [d...@wenandai.com](https://code.google.com/u/110119060265631073523/) on May 06, 2015 04:51:56_

any update?

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on May 09, 2015 02:32:57_

Do you want to submit a pull request? Otherwise I'd suggest to try to get it working with kryo or java serialization.
