### ISSUE TITLE
msm-javolution-serializer should support serialization of java.util.Collections$EmptyList

### ISSUE THREAD

**Issue by google-code-exporter** [magro/memcached-session-manager#72]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on January 04, 2010 00:16:26_

With version 1.1 of msm-javolution-serializer a 
java.util.Collections$EmptyList cannot be deserialized. When a session is 
loaded from memcached with such an element (class attribute), this fails 
with the following exception:

Jan 4, 2010 12:11:59 AM 
de.javakaffee.web.msm.serializer.javolution.ReflectionFormat readElements
SEVERE: Could not set field value for field private final java.util.List 
org.app.SomeClass._someField                                                                                            
javolution.xml.stream.XMLStreamException caused by 
java.lang.IllegalAccessException: Class javolution.xml.XMLFormat can not 
access a member of class java.util.Collections$EmptyList with modifiers 
"private"                                           
        at javolution.xml.XMLFormat.newInstance(XMLFormat.java:264)                                                         
        at 
javolution.xml.XMLFormat$InputElement.readInstanceOf(XMLFormat.java:499)                                         
        at javolution.xml.XMLFormat$InputElement.get(XMLFormat.java:403)                                                    
        at 
de.javakaffee.web.msm.serializer.javolution.ReflectionFormat.readElements(R
eflectionFormat.java:226)

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=28_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on January 03, 2010 16:06:38_

The same applies to Collections$EmptyMap.

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on January 03, 2010 16:30:27_

Fixed.

**Status:** Fixed  
  **Labels:** FixedIn1.1.1
