### ISSUE TITLE
msm-javolution-serializer should support serialization of java.util.Collections$UnmodifiableMap

### ISSUE THREAD

**Issue by google-code-exporter** [magro/memcached-session-manager#74]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on January 04, 2010 01:34:17_

msm-javolution-serializer in version 1.1 does not support deserialization 
of java.util.Collections$UnmodifiableMap, this fails with this exception:

Jan 4, 2010 1:29:34 AM 
de.javakaffee.web.msm.serializer.javolution.ReflectionFormat readElements
SEVERE: Could not set field value for field private java.util.Map 
org.app.SomeClass._someField                                                                                                              
java.lang.UnsupportedOperationException                                                                                     
        at java.util.Collections$UnmodifiableMap.put(Collections.java:1285)                                                 
        at 
de.javakaffee.web.msm.serializer.javolution.ReflectionBinding$XMLMapFormat.
read(ReflectionBinding.java:362)      
        at 
de.javakaffee.web.msm.serializer.javolution.ReflectionBinding$XMLMapFormat.
read(ReflectionBinding.java:329)      
        at 
javolution.xml.XMLFormat$InputElement.readInstanceOf(XMLFormat.java:507)                                         
        at javolution.xml.XMLFormat$InputElement.get(XMLFormat.java:403)

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=30_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on January 03, 2010 16:48:36_

Fixed.

**Status:** Fixed  
  **Labels:** FixedIn1.1.1
