### ISSUE TITLE
msm-javolution-serializer should be able to load classes from webapp context

### ISSUE THREAD

**Issue by google-code-exporter** [magro/memcached-session-manager#75]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on January 04, 2010 01:49:52_

msm-javolution-serializer in version 1.1 does not support deserialization 
of java.util.EnumSet, this fails with this exception:

Jan 4, 2010 1:47:32 AM 
de.javakaffee.web.msm.serializer.javolution.ReflectionFormat readElements
SEVERE: Could not set field value for field final java.lang.Class 
java.util.EnumSet.elementType 
javolution.xml.stream.XMLStreamException: Class null not found (see 
javolution.lang.Reflection) 
        at javolution.xml.XMLFormat$2.newInstance(XMLFormat.java:1128)                          
        at 
javolution.xml.XMLFormat$InputElement.readInstanceOf(XMLFormat.java:499)             
        at javolution.xml.XMLFormat$InputElement.get(XMLFormat.java:403)                        
        at 
de.javakaffee.web.msm.serializer.javolution.ReflectionFormat.readElements(R
eflectionFormat.java:226)
        at 
de.javakaffee.web.msm.serializer.javolution.ReflectionFormat.read(Reflectio
nFormat.java:205)        
        at 
javolution.xml.XMLFormat$InputElement.readInstanceOf(XMLFormat.java:507)

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=31_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on January 04, 2010 00:53:49_

This was caused by a class that was only visible in the webapp context (also indicated 
by "Class null not found").

**Summary:** msm-javolution-serializer should be able to load classes from webapp context

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on January 04, 2010 01:25:26_

Fixed.

**Status:** Fixed  
  **Labels:** FixedIn1.1.1
